[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version_scheme = "semver"
version = "5.0.0"
update_changelog_on_bump = true
version_files = [
  "backend/__version__.py",
  "backend/pyproject.toml",
  "frontend/package.json",
  "predict_occultation/__version__.py",
  ".VERSION"
]
