[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch$prerelease"
version_scheme = "semver"
version = "3.2.0"
update_changelog_on_bump = true
version_files = [
  "backend/__version__.py",
  "backend/pyproject.toml",
  "frontend/package.json",
  ".VERSION"
]
