repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      # - id: debug-statements
      # - id: check-builtin-literals
        # exclude: ^pipelines/
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^pipelines/
