version: "3.6"

services:
  # Database
  database:
    image: linea/postgresql_q3c:latest
    env_file:
      - .env

    expose:
      # Deixar a porta exposta para desenvolvimento
      # isto permite acessar o banco de dados a partir de outros apps como o DBeaver
      - 5432

    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data

  # Core Admin (Backend Django)
  backend:
    build: ./core_admin
    env_file:
      - .env

    volumes:
      - ./core_admin:/app
      - ${LOG_DIR}:/log
      - ${ARCHIVE_DIR}:/archive
      - ${PROCCESS_DIR}:/proccess
      - ${CCD_IMAGES_DIR}:/ccd_images
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database

  # Frontend React
  frontend:
    image: node:12.16.2
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: yarn start

  # Servidor Web NGINX
  nginx:
    build: ./frontend
    ports:
      - 80:8080
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    cap_drop:
      - ALL
    depends_on:
      - backend
      - frontend

​

# -------- Pipelines -----------

# Estao aqui apenas para garantir que as imagens vão ser baixadas
# antes da aplicação tentar executar.

# Praia Astrometry
  praia_astrometry:
    image: linea/tno_astrometry:v1.1.2
    volumes:
      - ${PROCCESS_DIR}:/data

  # NIMA
  nima:
    image: linea/nima:7
    volumes:
      - ${PROCCESS_DIR}:/data
​
  # Praia Occultation
  praia_occ:
    image: linea/praiaoccultation:v1.0.1
    volumes:
      - ${PROCCESS_DIR}:/data