version: "3.6"
services:
  # # Get Pointings
  # get-pointings:
  #   build: ./get_pointings
  #   ports:
  #     - 7005:7005

  # Filter Objects
  # filter-objects:
  #   build: ./filter_objects
  #   volumes:
  #   - ./filter_objects:/app
  #   environment:
  #     - DATABASE_URI
  #   ports:
  #     - 7008:7008
  #   networks:
  #     - backend

  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data
    networks:
      - backend

  # Core Admin (Backend Django)
  core-admin:
    build: ./core_admin
    image: tno-core-admin
    env_file:
      - .env
    volumes:
      - ./core_admin:/app
      - ${LOG_DIR}:/log
      - ${ARCHIVE_DIR}:/archive
      - ${PROCCESS_DIR}:/proccess
      - ${CCD_IMAGES_DIR}:/ccd_images
    ports:
      - 7001:7001
    networks:
      - backend
    depends_on:
      - database

  # Dashboard
  dashboard:
    build: ./dashboard
    image: tno-dashboard
    working_dir: /src/app
    ports:
      - 7000:7000
    networks:
      - backend
    command: ./entrypoint.sh

networks:
  backend:
# Baseado neste exemplo
# https://github.com/zackferrofields/docker-nginx-react/blob/develop/docker-compose.yml
