version: "3.6"
services:
  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data

  # Core Admin (Backend Django)
  backend:
    build: ./core_admin
    image: tno-backend
    env_file:
      - .env
    volumes:
      - ./core_admin:/app
      - ${LOG_DIR}:/log
      - ${ARCHIVE_DIR}:/archive
      - ${PROCCESS_DIR}:/proccess
      - ${CCD_IMAGES_DIR}:/ccd_images
    ports:
      - 7001:7001
    depends_on:
      - database

  # Dashboard
  frontend:
    build: ./dashboard
    image: tno-frontend
    working_dir: /src/app
    ports:
      - 7000:7000
    env_file:
      - .env      
    command: ./entrypoint.sh

  # NIMA
  nima:
    image: linea/nima:7
    volumes:
      - ${PROCCESS_DIR}:/data

  # Praia Occultation
  praia_occ:
    image: linea/praiaoccultation:latest
    volumes:
      - ${PROCCESS_DIR}:/data

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./frontend/build:/var/www/frontend
    cap_drop:
      - ALL
    depends_on:
      - frontend
      - backend