version: "3.6"
services:
  # Database
  database:
    image: linea/postgresql_q3c:latest
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data

  # Core Admin (Backend Django)
  backend:
    build: ./core_admin
    image: tno-backend
    env_file:
      - .env
    volumes:
      - ./core_admin:/app
      - ${LOG_DIR}:/log
      - ${ARCHIVE_DIR}:/archive
      - ${PROCCESS_DIR}:/proccess
      - ${CCD_IMAGES_DIR}:/ccd_images
    ports:
      - 7001:7001
    depends_on:
      - database

  # Praia Astrometry
  praia_astrometry:
    image: linea/tno_astrometry:latest
    volumes:
      - ${PROCCESS_DIR}:/data


  # NIMA
  nima:
    image: linea/nima:7
    volumes:
      - ${PROCCESS_DIR}:/data

  # Praia Occultation
  praia_occ:
    image: linea/praiaoccultation:latest
    volumes:
      - ${PROCCESS_DIR}:/data

  # Servidor Web NGINX
  frontend:
    build: ./dashboard
    ports:
      - 80:8080
    volumes:
      - ./dashboard/nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
    cap_drop:
      - ALL
    depends_on:
      - backend
