version: "3.6"
services:
  # # Get Pointings
  # get-pointings:
  #   build: ./get_pointings
  #   ports:
  #     - 7005:7005

  # Filter Objects
  # filter-objects:
  #   build: ./filter_objects
  #   volumes:
  #   - ./filter_objects:/app
  #   environment:
  #     - DATABASE_URI
  #   ports:
  #     - 7008:7008
  #   networks:
  #     - backend


  # Core Admin (Backend Django)
  core-admin:
    build: ./core_admin
    volumes:
      - ./core_admin:/app
    env_file:
      - .env
    ports:
      - 7001:7001
    networks:
      - backend

  # Dashboard
  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/src/app
      # - ./dashboard/node_modules:/src/app/node_modules
    working_dir: /src/app
    # links:
    #     - filter-objects
    depends_on:
      - filter-objects
    ports:
      - 7000:3000
    networks:
      - backend
    command: ./entrypoint.sh

networks:
  backend:
# Baseado neste exemplo
# https://github.com/zackferrofields/docker-nginx-react/blob/develop/docker-compose.yml
