# Generated by Django 2.2.13 on 2021-07-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occultation',
            name='asteroid',
        ),
        migrations.AlterUniqueTogether(
            name='predictasteroid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='predictasteroid',
            name='predict_run',
        ),
        migrations.RemoveField(
            model_name='predictinput',
            name='asteroid',
        ),
        migrations.RemoveField(
            model_name='predictoutput',
            name='asteroid',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='bsp_planetary',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='input_list',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='input_orbit',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='leap_second',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='process',
        ),
        migrations.DeleteModel(
            name='BspPlanetary',
        ),
        migrations.DeleteModel(
            name='LeapSecond',
        ),
        migrations.DeleteModel(
            name='Occultation',
        ),
        migrations.DeleteModel(
            name='PredictAsteroid',
        ),
        migrations.DeleteModel(
            name='PredictInput',
        ),
        migrations.DeleteModel(
            name='PredictOutput',
        ),
        migrations.DeleteModel(
            name='PredictRun',
        ),
    ]
