# Generated by Django 2.0.12 on 2020-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkybotYearResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=4, unique=True, verbose_name='Year')),
                ('nights', models.IntegerField(default=0, verbose_name='Nights with exposures')),
                ('exposures', models.IntegerField(default=0, verbose_name='Exposures')),
                ('ccds', models.IntegerField(default=0, verbose_name='CCDs with exposures')),
                ('nights_analyzed', models.IntegerField(default=0, verbose_name='Nights analyzed')),
                ('exposures_analyzed', models.IntegerField(default=0, verbose_name='Exposures analyzed')),
                ('ccds_analyzed', models.IntegerField(default=0, verbose_name='CCDs analyzed')),
            ],
        ),
    ]
