# Generated by Django 2.0.12 on 2020-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkybotDynclassResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynclass', models.CharField(choices=[('Centaur', 'Centaur'), ('Comet', 'Comet'), ('Hungaria', 'Hungaria'), ('KBO', 'KBO'), ('MB', 'MB'), ('Mars-Crosser', 'Mars-Crosser'), ('NEA', 'NEA'), ('Planet', 'Planet'), ('Trojan', 'Trojan')], max_length=12, unique=True, verbose_name='Dynamic Class')),
                ('nights', models.IntegerField(default=0, verbose_name='Nights')),
                ('ccds', models.IntegerField(default=0, verbose_name='CCDs')),
                ('asteroids', models.IntegerField(default=0, verbose_name='Asteroids')),
                ('positions', models.IntegerField(default=0, verbose_name='Positions')),
                ('u', models.IntegerField(default=0, verbose_name='Band u')),
                ('g', models.IntegerField(default=0, verbose_name='Band g')),
                ('r', models.IntegerField(default=0, verbose_name='Band r')),
                ('i', models.IntegerField(default=0, verbose_name='Band i')),
                ('z', models.IntegerField(default=0, verbose_name='Band z')),
                ('y', models.IntegerField(default=0, verbose_name='Band Y')),
            ],
        ),
    ]
