# Generated by Django 3.2.18 on 2024-02-16 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tno", "0001_squashed_0062_auto_20240215_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionjob",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tno.catalog",
                verbose_name="Catalog",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjob",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predicition_run",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
