# Generated by Django 3.2.18 on 2024-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0002_occultation_source_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occultation",
            name="source_id",
        ),
        migrations.AddField(
            model_name="occultation",
            name="gaia_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=None,
                help_text="GAIA source id Star candidate",
                null=True,
                verbose_name="GAIA Source ID",
            ),
        ),
    ]
