# Generated by Django 3.2.18 on 2024-02-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0002_auto_20240216_0017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occultation",
            name="apparent_magnitude",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Asteroids' apparent magnitude at the date (mag)",
                null=True,
                verbose_name="Apparent magnitude",
            ),
        ),
    ]
