# Generated by Django 3.2.18 on 2024-02-28 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0003_alter_occultation_apparent_magnitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionjob",
            name="leap_second",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tno.leapsecond",
                verbose_name="Leap Second",
            ),
        ),
        migrations.AddField(
            model_name="predictionjob",
            name="planetary_ephemeris",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tno.bspplanetary",
                verbose_name="Planetary Ephemeris",
            ),
        ),
    ]
