# Generated by Django 3.2.18 on 2024-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0003_auto_20240327_2023"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occultation",
            name="aparent_diameter",
        ),
        migrations.AddField(
            model_name="occultation",
            name="apparent_diameter",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Apparent diameter of the Earth as seen from the Asteroid (degrees)",
                null=True,
                verbose_name="apparent_diameter",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="event_duration",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Event duration (seconds)",
                null=True,
                verbose_name="event_duration",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="moon_separation",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Moon distance to the object (degrees)",
                null=True,
                verbose_name="moon_separation",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="sun_elongation",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Sun elongation (degrees)",
                null=True,
                verbose_name="sun_elongation",
            ),
        ),
    ]
