# Generated by Django 3.2.18 on 2024-08-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0004_auto_20240417_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="occultation",
            name="closest_approach_uncertainty",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Uncertainty in geocentric closest approach (arcsec)",
                null=True,
                verbose_name="Closest approach uncertainty",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="moon_illuminated_fraction",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Fraction of the Moon illuminated at the instant of the event",
                null=True,
                verbose_name="Moon illuminated fraction",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="probability_of_centrality",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Indicates the probability that the event will happen at the indicated path",
                null=True,
                verbose_name="Probability of centrality of the event",
            ),
        ),
        migrations.AlterField(
            model_name="occultation",
            name="catalog",
            field=models.CharField(
                blank=True,
                default="GAIA DR3",
                help_text="Catalog of stars used in prediction. for example GAIA DR2",
                max_length=10,
                null=True,
                verbose_name="Stellar Catalog",
            ),
        ),
    ]
