# Generated by Django 3.2.18 on 2024-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0005_auto_20240804_0208"),
    ]

    operations = [
        migrations.AddField(
            model_name="occultation",
            name="hash_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Unique hash identifier for the prediction event",
                max_length=26,
                null=True,
                unique=True,
                verbose_name="Hash ID",
            ),
        ),
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(
                fields=["hash_id"], name="tno_occulta_hash_id_ff09b7_idx"
            ),
        ),
    ]
