# Generated by Django 3.2.18 on 2024-08-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0005_alter_profile_dashboard"),
        ("tno", "0005_auto_20240804_0208"),
    ]

    operations = []
