# Generated by Django 3.2.18 on 2024-08-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0006_auto_20240822_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="occultation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
