# Generated by Django 3.2.18 on 2024-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0006_auto_20240822_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="occultation",
            name="closest_approach_uncertainty_km",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Uncertainty in geocentric closest approach (km)",
                null=True,
                verbose_name="Closest approach uncertainty in km",
            ),
        ),
    ]
