# Generated by Django 3.2 on 2023-01-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0009_auto_20230130_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='size',
        ),
    ]
