# Generated by Django 3.2.18 on 2025-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0009_highlights"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsteroidName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="(ucd=“meta.id;meta.main”) Object name (official or provisional designation).",
                        max_length=35,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "number",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).",
                        null=True,
                        verbose_name="Number",
                    ),
                ),
                (
                    "principal_designation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Principal designation assigned by the International Astronomical Union (IAU)",
                        max_length=35,
                        null=True,
                        verbose_name="Principal Designation",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=35,
                        null=True,
                        verbose_name="Alias used internally as an internal name, formed by the name without special characters and with the addition of sequential numbers if necessary.",
                    ),
                ),
            ],
        ),
    ]
