# Generated by Django 3.2.18 on 2025-02-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0010_asteroidname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AsteroidName",
            new_name="AsteroidCache",
        ),
    ]
