# Generated by Django 3.2.18 on 2025-02-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0012_auto_20250210_1730"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dynclasscache",
            unique_together={("skybot_dynbaseclass", "skybot_dynsubclass")},
        ),
    ]
