# Generated by Django 3.2.18 on 2025-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0013_alter_dynclasscache_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dynclasscache",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dynclasscache",
            constraint=models.UniqueConstraint(
                fields=("skybot_dynbaseclass", "skybot_dynsubclass"),
                name="unique_dynclass",
            ),
        ),
    ]
