# Generated by Django 3.2.18 on 2025-02-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0014_auto_20250210_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidcache",
            name="number",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).",
                max_length=35,
                verbose_name="Number",
            ),
        ),
    ]
