# Generated by Django 3.2.18 on 2025-02-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0015_alter_asteroidcache_number"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(fields=["loc_t"], name="tno_occulta_loc_t_6dfe20_idx"),
        ),
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(
                fields=["magnitude_drop"], name="tno_occulta_magnitu_7dbd2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(
                fields=["event_duration"], name="tno_occulta_event_d_044370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(
                fields=["closest_approach_uncertainty_km"],
                name="tno_occulta_closest_fd1f8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="occultation",
            index=models.Index(
                fields=["diameter"], name="tno_occulta_diamete_2d147f_idx"
            ),
        ),
    ]
