# Generated by Django 3.2.18 on 2023-03-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0016_auto_20230306_2014"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionJobResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asteroid_name",
                    models.CharField(max_length=100, verbose_name="Asteroid Name"),
                ),
                (
                    "asteroid_number",
                    models.CharField(max_length=100, verbose_name="Asteroid Number"),
                ),
                ("des_obs", models.IntegerField(default=0, verbose_name="des_obs")),
                (
                    "des_obs_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="des_obs_start"
                    ),
                ),
                (
                    "des_obs_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="des_obs_finish"
                    ),
                ),
                (
                    "des_obs_exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="des_obs_exec_time"
                    ),
                ),
                (
                    "des_obs_gen_run",
                    models.BooleanField(default=False, verbose_name="des_obs_gen_run"),
                ),
                (
                    "des_obs_tp_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="des_obs_tp_start"
                    ),
                ),
                (
                    "des_obs_tp_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="des_obs_tp_finish"
                    ),
                ),
                (
                    "bsp_jpl_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bsp_jpl_start"
                    ),
                ),
                (
                    "bsp_jpl_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bsp_jpl_finish"
                    ),
                ),
                (
                    "bsp_jpl_dw_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="bsp_jpl_dw_time"
                    ),
                ),
                (
                    "bsp_jpl_dw_run",
                    models.BooleanField(default=False, verbose_name="bsp_jpl_dw_run"),
                ),
                (
                    "bsp_jpl_tp_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bsp_jpl_tp_start"
                    ),
                ),
                (
                    "bsp_jpl_tp_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bsp_jpl_tp_finish"
                    ),
                ),
                (
                    "obs_source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="obs_source"
                    ),
                ),
                (
                    "obs_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_start"
                    ),
                ),
                (
                    "obs_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_finish"
                    ),
                ),
                (
                    "obs_dw_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="obs_dw_time"
                    ),
                ),
                (
                    "obs_dw_run",
                    models.BooleanField(default=False, verbose_name="obs_dw_run"),
                ),
                (
                    "obs_tp_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_tp_start"
                    ),
                ),
                (
                    "obs_tp_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_tp_finish"
                    ),
                ),
                (
                    "obs_ele_source",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="obs_ele_source",
                    ),
                ),
                (
                    "obs_ele_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_ele_start"
                    ),
                ),
                (
                    "obs_ele_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_ele_finish"
                    ),
                ),
                (
                    "obs_ele_dw_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="obs_ele_dw_time"
                    ),
                ),
                (
                    "obs_ele_dw_run",
                    models.BooleanField(default=False, verbose_name="obs_ele_dw_run"),
                ),
                (
                    "obs_ele_tp_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_ele_tp_start"
                    ),
                ),
                (
                    "obs_ele_tp_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="obs_ele_tp_finish"
                    ),
                ),
                (
                    "ref_orb_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ref_orb_start"
                    ),
                ),
                (
                    "ref_orb_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ref_orb_finish"
                    ),
                ),
                (
                    "ref_orb_exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="ref_orb_exec_time"
                    ),
                ),
                (
                    "pre_occ_count",
                    models.IntegerField(default=0, verbose_name="pre_occ_count"),
                ),
                (
                    "pre_occ_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="pre_occ_start"
                    ),
                ),
                (
                    "pre_occ_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="pre_occ_finish"
                    ),
                ),
                (
                    "pre_occ_exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="pre_occ_exec_time"
                    ),
                ),
                (
                    "ing_occ_count",
                    models.IntegerField(default=0, verbose_name="ing_occ_count"),
                ),
                (
                    "ing_occ_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ing_occ_start"
                    ),
                ),
                (
                    "ing_occ_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ing_occ_finish"
                    ),
                ),
                (
                    "ing_occ_exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="ing_occ_exec_time"
                    ),
                ),
                (
                    "messages",
                    models.TextField(blank=True, null=True, verbose_name="messages"),
                ),
                (
                    "asteroid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.asteroid",
                        verbose_name="Asteroid",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.predictionjob",
                        verbose_name="Orbit Trace Job",
                    ),
                ),
            ],
        ),
    ]
