# Generated by Django 3.2.18 on 2025-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0016_auto_20250210_2040"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="bsp_jpl_dw_time",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="bsp_jpl_finish",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="bsp_jpl_start",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="des_obs",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="des_obs_exec_time",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="des_obs_finish",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="des_obs_start",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="obs_dw_time",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="obs_finish",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="obs_source",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="obs_start",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="orb_ele_dw_time",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="orb_ele_finish",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="orb_ele_source",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="orb_ele_start",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="ref_orb_exec_time",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="ref_orb_finish",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="ref_orb_start",
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="exec_time",
            field=models.DurationField(
                blank=True,
                default=0,
                help_text="Prediction pipeline runtime for this asteroid.",
                null=True,
                verbose_name="exec_time",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Success"),
                    (2, "Failed"),
                    (3, "Queued"),
                    (4, "Running"),
                    (5, "Aborted"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
