# Generated by Django 3.2.18 on 2025-02-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0017_auto_20250214_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionjobresult",
            name="occultations",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of occultation events identified for this asteroid.",
                null=True,
                verbose_name="Occultations",
            ),
        ),
    ]
