# Generated by Django 3.2.18 on 2025-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0018_alter_predictionjobresult_occultations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionjobresult",
            name="ing_occ_count",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Total Occultations registered in the database.",
                null=True,
                verbose_name="Occultations Ingested",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="ing_occ_exec_time",
            field=models.DurationField(
                blank=True,
                default=0,
                help_text="Execution time of the results ingestion step.",
                null=True,
                verbose_name="Result Ingestion Execution Time",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="messages",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Error messages that occurred while running this asteroid, there may be more than one in this case will be separated by ;",
                null=True,
                verbose_name="messages",
            ),
        ),
    ]
