# Generated by Django 3.2.18 on 2023-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0019_auto_20230314_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionjobresult',
            name='exec_time',
            field=models.DurationField(blank=True, null=True, verbose_name='exec_time'),
        ),
    ]
