# Generated by Django 3.2.18 on 2025-02-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0019_auto_20250214_1803"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occultation",
            name="obs_source",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="orb_ele_source",
        ),
    ]
