# Generated by Django 3.2.18 on 2023-03-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0020_predictionjobresult_exec_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionjob",
            name="catalog",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tno.catalog",
                verbose_name="Catalog",
            ),
            preserve_default=False,
        ),
    ]
