# Generated by Django 3.2.18 on 2025-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0020_auto_20250214_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionjobresult",
            name="stars",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of stars processed for this asteroid.",
                null=True,
                verbose_name="Stars",
            ),
        ),
    ]
