# Generated by Django 3.2.18 on 2025-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0021_predictionjobresult_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionjob",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Idle"),
                    (2, "Running"),
                    (3, "Completed"),
                    (4, "Failed"),
                    (5, "Aborted"),
                    (6, "Warning"),
                    (7, "Aborting"),
                    (8, "Consolidating"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Success"),
                    (2, "Failed"),
                    (3, "Queued"),
                    (4, "Running"),
                    (5, "Aborted"),
                    (6, "Ingesting"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
