# Generated by Django 3.2.18 on 2025-07-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0022_auto_20250717_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occultation",
            name="bsp_source",
            field=models.CharField(
                blank=True,
                default="Unavailable",
                help_text="Asteroid Bsp ephemeris data source. for example JPL.",
                max_length=35,
                null=True,
                verbose_name="Bsp Source",
            ),
        ),
    ]
