# Generated by Django 3.2.18 on 2023-05-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0023_auto_20230523_2359"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_dw_run",
            new_name="orb_ele_dw_run",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_dw_time",
            new_name="orb_ele_dw_time",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_finish",
            new_name="orb_ele_finish",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_source",
            new_name="orb_ele_source",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_start",
            new_name="orb_ele_start",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_tp_finish",
            new_name="orb_ele_tp_finish",
        ),
        migrations.RenameField(
            model_name="predictionjobresult",
            old_name="obs_ele_tp_start",
            new_name="orb_ele_tp_start",
        ),
        migrations.RemoveField(
            model_name="predictionjobresult",
            name="pre_occ_count",
        ),
        migrations.AddField(
            model_name="predictionjobresult",
            name="occultations",
            field=models.IntegerField(
                default=0,
                help_text="Number of occultation events identified for this asteroid.",
                verbose_name="Occultations",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="des_obs",
            field=models.IntegerField(
                default=0,
                help_text="total DES observations for this asteroid.",
                verbose_name="des_obs",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="exec_time",
            field=models.DurationField(
                blank=True,
                help_text="Prediction pipeline runtime for this asteroid.",
                null=True,
                verbose_name="exec_time",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="messages",
            field=models.TextField(
                blank=True,
                help_text="Error messages that occurred while running this asteroid, there may be more than one in this case will be separated by ;",
                null=True,
                verbose_name="messages",
            ),
        ),
        migrations.AlterField(
            model_name="predictionjobresult",
            name="obs_source",
            field=models.CharField(
                blank=True,
                help_text="Observation data source, AstDys or MPC.",
                max_length=100,
                null=True,
                verbose_name="Observation Source",
            ),
        ),
    ]
