# Generated by Django 3.2.18 on 2026-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0023_alter_occultation_bsp_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leapsecond",
            options={
                "ordering": ["id"],
                "verbose_name": "Leap Second",
                "verbose_name_plural": "Leap Second",
            },
        ),
    ]
