# Generated by Django 3.2.18 on 2025-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0023_alter_occultation_bsp_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BspAsteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=35, verbose_name='Name')),
                ('number', models.PositiveBigIntegerField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', null=True, verbose_name='Number')),
                ('principal_designation', models.CharField(blank=True, default=None, help_text='Principal designation assigned by the International Astronomical Union (IAU)', max_length=35, null=True, verbose_name='Principal Designation')),
                ('alias', models.CharField(blank=True, default=None, help_text='Alias used internally as an internal name, formed by the name without special characters and with the addition of sequential numbers if necessary.', max_length=35, null=True, verbose_name='Alias')),
                ('base_dynclass', models.CharField(blank=True, default=None, help_text="(ucd=“meta.code.class”) Object's base dynamical classification as defined by Skybot (KBO, Centaur, Trojan, MB, etc.).", max_length=24, null=True, verbose_name="Object's base dynamical classification as defined by Skybot")),
                ('dynclass', models.CharField(blank=True, default=None, help_text="(ucd=“meta.code.class;src.class”) Object's dynamical subclass as defined by Skybot (KBO>Resonant>12:5, MB>Inner, etc.).", max_length=24, null=True, verbose_name="Object's dynamical subclass as defined by Skybot")),
                ('source', models.CharField(default='JPL', help_text="Source of the BSP data. Possible values: 'JPL', 'NIMA'.", max_length=5, verbose_name='Source')),
                ('spkid', models.CharField(blank=True, default=None, max_length=35, null=True, verbose_name='SPKID')),
                ('filename', models.CharField(help_text='Name of the BSP file associated with this asteroid.', max_length=255, verbose_name='Filename')),
                ('start_period', models.DateField(help_text='Start date of the period covered by the BSP file.', verbose_name='Start Period')),
                ('end_period', models.DateField(help_text='End date of the period covered by the BSP file.', verbose_name='End Period')),
                ('size', models.PositiveIntegerField(help_text='Size of the BSP file in bytes.', verbose_name='Size (bytes)')),
                ('mag_and_uncert_filename', models.CharField(help_text='Name of the file containing magnitude and uncertainty data associated with this asteroid.', max_length=255, verbose_name='Magnitude and Uncertainty Filename')),
                ('mag_and_uncert_size', models.PositiveIntegerField(help_text='Size of the magnitude and uncertainty file in bytes.', verbose_name='Magnitude and Uncertainty File Size (bytes)')),
                ('dw_start', models.DateTimeField(blank=True, default=None, help_text='Timestamp of the start download of this BSP file.', null=True, verbose_name='Download Start Time')),
                ('dw_finish', models.DateTimeField(blank=True, default=None, help_text='Timestamp of the finish download of this BSP file.', null=True, verbose_name='Download Finish Time')),
                ('dw_time', models.FloatField(default=0, help_text='Total time taken to download the BSP file, in seconds.', verbose_name='Download Time (seconds)')),
            ],
        ),
    ]
