# Generated by Django 3.2.18 on 2025-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0024_bspasteroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='alias',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=35, null=True, verbose_name='Alias used internally as an internal name, formed by the name without special characters and with the addition of sequential numbers if necessary.'),
        ),
    ]
