# Generated by Django 3.2.18 on 2025-10-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0025_alter_asteroid_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='bspasteroid',
            name='orbit_id',
            field=models.CharField(blank=True, default=None, help_text='Identifier for the specific orbit solution used to generate the BSP file.', max_length=35, null=True, verbose_name='Orbit ID'),
        ),
    ]
