# Generated by Django 3.2.18 on 2023-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0026_auto_20230524_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occultation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
