# Generated by Django 3.2.18 on 2025-10-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0026_bspasteroid_orbit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bspasteroid',
            name='alias',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Alias used internally as an internal name, formed by the name without special characters and with the addition of sequential numbers if necessary.', max_length=35, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='bspasteroid',
            name='base_dynclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="(ucd=“meta.code.class”) Object's base dynamical classification as defined by Skybot (KBO, Centaur, Trojan, MB, etc.).", max_length=24, null=True, verbose_name="Object's base dynamical classification as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='bspasteroid',
            name='dynclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="(ucd=“meta.code.class;src.class”) Object's dynamical subclass as defined by Skybot (KBO>Resonant>12:5, MB>Inner, etc.).", max_length=24, null=True, verbose_name="Object's dynamical subclass as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='bspasteroid',
            name='name',
            field=models.CharField(db_index=True, help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=35, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bspasteroid',
            name='principal_designation',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Principal designation assigned by the International Astronomical Union (IAU)', max_length=35, null=True, verbose_name='Principal Designation'),
        ),
    ]
