# Generated by Django 3.2.18 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0028_auto_20230526_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionjobresult',
            name='bsp_jpl_dw_time',
            field=models.DurationField(blank=True, help_text='BSP download time from JPL.', null=True, verbose_name='BSP JPL download time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='bsp_jpl_finish',
            field=models.DateTimeField(blank=True, help_text='End of the Dwonload stage of the JPL BSP.', null=True, verbose_name='BSP JPL finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='bsp_jpl_start',
            field=models.DateTimeField(blank=True, help_text='Beginning of the JPL BSP Download step.', null=True, verbose_name='BSP JPL start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='des_obs_exec_time',
            field=models.DurationField(blank=True, help_text='DES Observations step execution time in seconds.', null=True, verbose_name='DES Observations Execution Time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='des_obs_finish',
            field=models.DateTimeField(blank=True, help_text='End of the DES Observations stage', null=True, verbose_name='DES Observations Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='des_obs_start',
            field=models.DateTimeField(blank=True, help_text='Start of the execution of the DES Observations step', null=True, verbose_name='DES Observations Start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ing_occ_count',
            field=models.IntegerField(default=0, help_text='Total Occultations registered in the database.', verbose_name='Occultations Ingested'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ing_occ_exec_time',
            field=models.DurationField(blank=True, help_text='Execution time of the results ingestion step.', null=True, verbose_name='Result Ingestion Execution Time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ing_occ_finish',
            field=models.DateTimeField(blank=True, help_text='End of record of results.', null=True, verbose_name='Result Ingestion Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ing_occ_start',
            field=models.DateTimeField(blank=True, help_text='Start recording the results.', null=True, verbose_name='Result Ingestion Start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='obs_dw_time',
            field=models.DurationField(blank=True, help_text='Observations download time.', null=True, verbose_name='Observations Download Time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='obs_finish',
            field=models.DateTimeField(blank=True, help_text='End of the Download stage of the observations.', null=True, verbose_name='Observations Download Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='obs_start',
            field=models.DateTimeField(blank=True, help_text='Beginning of the Download stage of observations.', null=True, verbose_name='Observations Download Start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='orb_ele_dw_time',
            field=models.DurationField(blank=True, help_text='Orbital Elements download time.', null=True, verbose_name='Orbital Elements Download Time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='orb_ele_finish',
            field=models.DateTimeField(blank=True, help_text='End of Orbital Elements Download step.', null=True, verbose_name='Orbital Elements Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='orb_ele_start',
            field=models.DateTimeField(blank=True, help_text='Beginning of the Orbtial Elements Download stage.', null=True, verbose_name='Orbital Elements Start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='pre_occ_exec_time',
            field=models.DurationField(blank=True, help_text='Predict Occultation runtime.', null=True, verbose_name='Predict Occultation Execution Time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='pre_occ_finish',
            field=models.DateTimeField(blank=True, help_text='End of the Predict Occultation step.', null=True, verbose_name='Predict Occultation Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='pre_occ_start',
            field=models.DateTimeField(blank=True, help_text='Start of the Predict Occultation step.', null=True, verbose_name='Predict Occultation Start'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ref_orb_exec_time',
            field=models.DurationField(blank=True, help_text='Refine Orbit runtime.', null=True, verbose_name='Refine Orbit execution time'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ref_orb_finish',
            field=models.DateTimeField(blank=True, help_text='End of the Refine Orbit step.', null=True, verbose_name='Refine Orbit Finish'),
        ),
        migrations.AlterField(
            model_name='predictionjobresult',
            name='ref_orb_start',
            field=models.DateTimeField(blank=True, help_text='Start of the Refine Orbit step.', null=True, verbose_name='Refine Orbit Start'),
        ),
    ]
