# Generated by Django 3.2.18 on 2023-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0029_auto_20230529_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionjob',
            name='predict_h_period',
            field=models.CharField(blank=True, default=None, help_text='Prediction range formatted with humanize.', max_length=100, null=True, verbose_name='Predict Period'),
        ),
    ]
