# Generated by Django 3.2.18 on 2023-06-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0032_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionJobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        choices=[(1, "Primeira Etapa"), (2, "Segunda Etapa")],
                        help_text="Identification of the step in the pipeline.",
                        verbose_name="Step",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Idle"),
                            (2, "Running"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Aborted"),
                            (6, "Warning"),
                            (7, "Aborting"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Total items to be processed in the step.",
                        verbose_name="Total Count",
                    ),
                ),
                (
                    "current",
                    models.IntegerField(
                        default=0,
                        help_text="Current position in execution.",
                        verbose_name="Total Count",
                    ),
                ),
                (
                    "average_time",
                    models.FloatField(
                        default=0,
                        help_text="Average time per item in seconds.",
                        verbose_name="Average Time",
                    ),
                ),
                (
                    "time_estimate",
                    models.FloatField(
                        default=0,
                        help_text="Estimated time to complete the step in seconds.",
                        verbose_name="Estimated Time",
                    ),
                ),
                (
                    "success",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items successfully executed.",
                        verbose_name="Success",
                    ),
                ),
                (
                    "failures",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items that failed.",
                        verbose_name="Failures",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.predictionjob",
                        verbose_name="Prediction Job",
                    ),
                ),
            ],
        ),
    ]
