# Generated by Django 3.2.18 on 2023-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0033_predictionjobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionjobstatus',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='predictionjobstatus',
            name='current',
            field=models.IntegerField(default=0, help_text='Current position in execution.', verbose_name='Current'),
        ),
    ]
