# Generated by Django 3.2.18 on 2023-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0035_predictionjobstatus_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='occultation',
            name='aparent_diameter',
            field=models.FloatField(blank=True, default=None, help_text='Aparent diameter', null=True, verbose_name='aparent_diameter'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='aphelion',
            field=models.FloatField(blank=True, default=0, help_text='Aphelion', null=True, verbose_name='Aphelion'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='apparent_magnitude',
            field=models.CharField(blank=True, default=None, help_text='Apparent magnitude', max_length=35, null=True, verbose_name='Apparent magnitude'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='dec_star_to_date',
            field=models.CharField(blank=True, default=None, help_text='dec_star_to_date', max_length=35, null=True, verbose_name='dec_star_to_date'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='dec_star_with_pm',
            field=models.CharField(blank=True, default=None, help_text='dec_star_with_pm', max_length=35, null=True, verbose_name='dec_star_with_pm'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='dec_target_apparent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='dec_target_apparent'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='diameter',
            field=models.FloatField(blank=True, default=None, help_text='Diameter', null=True, verbose_name='diameter'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='dynamic_class',
            field=models.CharField(blank=True, default=None, help_text='Dynamic class', max_length=35, null=True, verbose_name='Dynamic class'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='e_dec_target',
            field=models.FloatField(blank=True, default=0, help_text='E_dec_target', null=True, verbose_name='E_dec_target'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='e_ra_target',
            field=models.FloatField(blank=True, default=0, help_text='E_ra_target', null=True, verbose_name='E_ra_target'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='eccentricity',
            field=models.FloatField(blank=True, default=0, help_text='Eccentricity', null=True, verbose_name='Eccentricity'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='ephemeris_version',
            field=models.CharField(blank=True, default=None, help_text='Ephemeris version', max_length=35, null=True, verbose_name='Ephemeris version'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='g_mag_vel_corrected',
            field=models.FloatField(blank=True, default=None, help_text='Gaia magnitude corrected from velocity', null=True, verbose_name='g_mag_vel_corrected'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='h_mag_vel_corrected',
            field=models.FloatField(blank=True, default=None, help_text='2MASS H magnitude corrected from velocity', null=True, verbose_name='h_mag_vel_corrected'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='inclination',
            field=models.FloatField(blank=True, default=0, help_text='Inclination', null=True, verbose_name='Inclination'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='instant_uncertainty',
            field=models.FloatField(blank=True, default=None, help_text='Instant uncertainty', null=True, verbose_name='instant_uncertainty'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='magnitude_drop',
            field=models.FloatField(blank=True, default=None, help_text='Magnitude drop', null=True, verbose_name='magnitude_drop'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='perihelion',
            field=models.FloatField(blank=True, default=0, help_text='Perihelion', null=True, verbose_name='Perihelion'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='ra_star_to_date',
            field=models.CharField(blank=True, default=None, help_text='ra_star_to_date', max_length=35, null=True, verbose_name='ra_star_to_date'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='ra_star_with_pm',
            field=models.CharField(blank=True, default=None, help_text='ra_star_with_pm', max_length=35, null=True, verbose_name='ra_star_with_pm'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='ra_target_apparent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ra_target_apparent'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='rp_mag_vel_corrected',
            field=models.FloatField(blank=True, default=None, help_text='Gaia RP magnitude corrected from velocity', null=True, verbose_name='rp_mag_vel_corrected'),
        ),
        migrations.AddField(
            model_name='occultation',
            name='semimajor_axis',
            field=models.FloatField(blank=True, default=0, help_text='Semimajor axis', null=True, verbose_name='Semimajor axis'),
        ),
    ]
