# Generated by Django 3.2.18 on 2023-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0040_auto_20231016_1606"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occultation",
            old_name="occultation_path_coeff",
            new_name="occ_path_coeff",
        ),
        migrations.RenameField(
            model_name="occultation",
            old_name="max_longitude",
            new_name="occ_path_max_longitude",
        ),
        migrations.RenameField(
            model_name="occultation",
            old_name="min_longitude",
            new_name="occ_path_min_longitude",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="dynamic_class",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="max_latitude",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="min_latitude",
        ),
        migrations.AddField(
            model_name="occultation",
            name="occ_path_is_nightside",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True if any part of the path occurs at night",
                null=True,
                verbose_name="Occultation Path Nightside",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="occ_path_max_latitude",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Max Latitude Occultation Path. -180 +180",
                null=True,
                verbose_name="Max Latitude",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="occ_path_min_latitude",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Min Latitude Occultation Path. -180 +180",
                null=True,
                verbose_name="Min Latitude",
            ),
        ),
    ]
