# Generated by Django 3.2.18 on 2023-10-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0042_auto_20231023_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='number',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=35, null=True, verbose_name='Number'),
        ),
    ]
