# Generated by Django 3.2.18 on 2024-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0043_alter_asteroid_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="occultation",
            name="base_dynclass",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="(ucd=“meta.code.class”) Base Object class (TNO, Centaur, Trojan, etc.).",
                max_length=24,
                null=True,
                verbose_name="Base Object classification",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="bsp_planetary",
            field=models.CharField(
                blank=True,
                default="de440",
                help_text="File/version of planetary ephemeris used.",
                max_length=10,
                null=True,
                verbose_name="Planetary Ephemeris",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="bsp_source",
            field=models.CharField(
                blank=True,
                default="JPL",
                help_text="Asteroid Bsp ephemeris data source. for example JPL.",
                max_length=10,
                null=True,
                verbose_name="Bsp Source",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="catalog",
            field=models.CharField(
                blank=True,
                default="GAIA DR2",
                help_text="Catalog of stars used in prediction. for example GAIA DR2",
                max_length=10,
                null=True,
                verbose_name="Stellar Catalog",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="dynclass",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="(ucd=“meta.code.class;src.class”) Object class (TNO, Centaur, Trojan, etc.).",
                max_length=24,
                null=True,
                verbose_name="Object classification",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="job_id",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Identification of the prediction job that generated this prediction.",
                null=True,
                verbose_name="Prediction Job",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="leap_seconds",
            field=models.CharField(
                blank=True,
                default="naif0012",
                help_text="File/version of Leap Seconds used.",
                max_length=10,
                null=True,
                verbose_name="Leap Seconds",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="nima",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="True if the prediction used NIMA results.",
                null=True,
                verbose_name="NIMA",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="obs_source",
            field=models.CharField(
                blank=True,
                default="MPC",
                help_text="Observation data source, AstDys or MPC.",
                max_length=10,
                null=True,
                verbose_name="Observation Source",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="orb_ele_source",
            field=models.CharField(
                blank=True,
                default="MPC",
                help_text="Orbital Elements data source, AstDys or MPC.",
                max_length=10,
                null=True,
                verbose_name="Orbital Elements Source",
            ),
        ),
        migrations.AddField(
            model_name="occultation",
            name="predict_step",
            field=models.IntegerField(
                blank=True,
                default=600,
                help_text="Prediction Step",
                null=True,
                verbose_name="Prediction Step",
            ),
        ),
    ]
