# Generated by Django 3.2.18 on 2024-01-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0051_alter_asteroid_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidjob',
            name='submit_time',
        ),
    ]
