# Generated by Django 3.2.18 on 2024-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0057_auto_20240131_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occultation',
            name='mpc_critical_list',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='MPC critical list'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='pha_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='pha_flag'),
        ),
    ]
