# Generated by Django 3.2.18 on 2024-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0059_auto_20240205_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='albedo',
            field=models.FloatField(blank=True, default=None, help_text="Asteroid's surface reflectivity or brightness.", null=True, verbose_name='albedo'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='albedo_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Albedo upper error', null=True, verbose_name='albedo_err_max'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='albedo_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Albedo lower error', null=True, verbose_name='albedo_err_min'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='aphelion_dist',
            field=models.FloatField(blank=True, default=None, help_text='Aphelion distance (AU)', null=True, verbose_name='Aphelion distance'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='arg_perihelion',
            field=models.FloatField(blank=True, default=None, help_text='Argument of perihelion, J2000.0 (degrees)', null=True, verbose_name='Argument of perihelion'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='astorb_dynbaseclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Object's base dynamical classification as defined by AstOrb (Lowell Observatory)", max_length=35, null=True, verbose_name="Object's base dynamical classification as defined by AstOrb"),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='astorb_dynsubclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Object's dynamical subclass as defined by AstOrb (Lowell Observatory)", max_length=35, null=True, verbose_name="Object's dynamical subclass as defined by AstOrb"),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='base_dynclass',
            field=models.CharField(db_index=True, help_text="(ucd=“meta.code.class”) Object's base dynamical classification as defined by Skybot (KBO, Centaur, Trojan, MB, etc.).", max_length=35, verbose_name="Object's base dynamical classification as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='density',
            field=models.FloatField(blank=True, default=None, help_text='Density (kg/m^3)', null=True, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='density_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Density upper error (kg/m^3)', null=True, verbose_name='density_err_max'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='density_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Density lower error (kg/m^3)', null=True, verbose_name='density_err_min'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='diameter',
            field=models.FloatField(blank=True, default=None, help_text='Diameter (km)', null=True, verbose_name='diameter'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='diameter_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Diameter upper error (km)', null=True, verbose_name='diameter_err_max'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='diameter_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Diameter lower error (km)', null=True, verbose_name='diameter_err_min'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='dynclass',
            field=models.CharField(db_index=True, help_text="(ucd=“meta.code.class;src.class”) Object's dynamical subclass as defined by Skybot (KBO>Resonant>12:5, MB>Inner, etc.).", max_length=35, verbose_name="Object's dynamical subclass as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='epoch',
            field=models.FloatField(blank=True, default=None, help_text='Epoch of the orbit (Julian Date)', null=True, verbose_name='Epoch of the orbit'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='excentricity',
            field=models.FloatField(blank=True, default=None, help_text='Excentricity', null=True, verbose_name='Excentricity'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='g',
            field=models.FloatField(blank=True, default=None, help_text='Phase slope parameter', null=True, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='h',
            field=models.FloatField(blank=True, default=None, help_text='Absolute magnitude', null=True, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='inclination',
            field=models.FloatField(blank=True, default=None, help_text='Inclination (degres)', null=True, verbose_name='Inclination'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_obs_included',
            field=models.DateField(blank=True, default=None, help_text='Date of last observation included in MPC orbit solution (YYYY-MM-DD format)', null=True, verbose_name='Date of last observation included'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='long_asc_node',
            field=models.FloatField(blank=True, default=None, help_text='Longitude of the ascending node, J2000.0 (degrees)', null=True, verbose_name='Longitude of the ascending node'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mass',
            field=models.FloatField(blank=True, default=None, help_text='Mass (kg)', null=True, verbose_name='mass'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mass_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Mass upper error (kg)', null=True, verbose_name='mass_err_max'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mass_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Mass lower error (kg)', null=True, verbose_name='mass_err_min'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mean_anomaly',
            field=models.FloatField(blank=True, default=None, help_text='Mean anomaly at the epoch (degrees)', null=True, verbose_name='Mean anomaly'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mean_daily_motion',
            field=models.FloatField(blank=True, default=None, help_text='Mean daily motion (degrees/day)', null=True, verbose_name='Mean daily motion'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='mpc_critical_list',
            field=models.BooleanField(default=False, help_text='Critical objects numbered on the MPC list are those whose orbits require improvement', verbose_name='mpc_critical_list'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='perihelion_dist',
            field=models.FloatField(blank=True, default=None, help_text='Perihelion distance (AU)', null=True, verbose_name='Perihelion distance'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='pha_flag',
            field=models.BooleanField(default=False, help_text='Potentially Hazardous Asteroid Flag', verbose_name='pha_flag'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='principal_designation',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Principal designation assigned by the International Astronomical Union (IAU)', max_length=35, null=True, verbose_name='Principal Designation'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='rms',
            field=models.FloatField(blank=True, default=None, help_text='r.m.s. residual of the fit (arcsec)', null=True, verbose_name='r.m.s. residual'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='semimajor_axis',
            field=models.FloatField(blank=True, default=None, help_text='Semimajor axis (AU)', null=True, verbose_name='Semimajor axis'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='albedo',
            field=models.FloatField(blank=True, default=None, help_text='Albedo', null=True, verbose_name='albedo'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='albedo_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Albedo upper error', null=True, verbose_name='albedo_err_max'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='albedo_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Albedo lower error', null=True, verbose_name='albedo_err_min'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='aparent_diameter',
            field=models.FloatField(blank=True, default=None, help_text='Apparent diameter of the Earth as seen from the Asteroid (degrees)', null=True, verbose_name='aparent_diameter'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='aphelion',
            field=models.FloatField(blank=True, default=None, help_text='Aphelion (AU)', null=True, verbose_name='Aphelion'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='aphelion_dist',
            field=models.FloatField(blank=True, default=None, help_text='Aphelion distance (AU)', null=True, verbose_name='Aphelion distance'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='apparent_magnitude',
            field=models.CharField(blank=True, default=None, help_text="Asteroids' apparent magnitude at the date (mag)", max_length=35, null=True, verbose_name='Apparent magnitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='arg_perihelion',
            field=models.FloatField(blank=True, default=None, help_text='Argument of perihelion, J2000.0 (degrees)', null=True, verbose_name='Argument of perihelion'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='astorb_dynbaseclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Object's base dynamical classification as defined by AstOrb (Lowell Observatory)", max_length=35, null=True, verbose_name="Object's base dynamical classification as defined by AstOrb"),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='astorb_dynsubclass',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Object's dynamical subclass as defined by AstOrb (Lowell Observatory)", max_length=35, null=True, verbose_name="Object's dynamical subclass as defined by AstOrb"),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='base_dynclass',
            field=models.CharField(blank=True, default=None, help_text="(ucd=“meta.code.class”) Object's base dynamical classification as defined by Skybot (KBO, Centaur, Trojan, MB, etc.).", max_length=24, null=True, verbose_name="Object's base dynamical classification as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='closest_approach',
            field=models.FloatField(default=0, help_text='Geocentric closest approach (arcsec)', verbose_name='Closest approach'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ct',
            field=models.CharField(blank=True, default=None, help_text='Only Gaia DR1 stars are used', max_length=10, null=True, verbose_name='ct'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_star_candidate',
            field=models.CharField(help_text='Star candidate declination (dd:mm:ss)', max_length=20, verbose_name='Dec Star Candidate'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_star_deg',
            field=models.FloatField(blank=True, help_text="Star's declination (degrees)", null=True, verbose_name='Dec Star deg'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_star_to_date',
            field=models.CharField(blank=True, default=None, help_text="Star's declination reduced to date", max_length=35, null=True, verbose_name='dec_star_to_date'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_star_with_pm',
            field=models.CharField(blank=True, default=None, help_text="Star's declination corrected for proper motion", max_length=35, null=True, verbose_name='dec_star_with_pm'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_target',
            field=models.CharField(help_text="Target's declination (dd:mm:ss)", max_length=20, verbose_name='Dec Target'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_target_apparent',
            field=models.CharField(blank=True, help_text="Target's apparent declination", max_length=20, null=True, verbose_name='dec_target_apparent'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dec_target_deg',
            field=models.FloatField(blank=True, help_text="Target's declination (degrees)", null=True, verbose_name='Dec Target deg'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='density',
            field=models.FloatField(blank=True, default=None, help_text='Density (kg/m^3)', null=True, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='density_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Density upper error (kg/m^3)', null=True, verbose_name='density_err_max'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='density_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Density lower error (kg/m^3)', null=True, verbose_name='density_err_min'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='diameter',
            field=models.FloatField(blank=True, default=None, help_text='Diameter (km)', null=True, verbose_name='diameter'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='diameter_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Diameter upper error (km)', null=True, verbose_name='diameter_err_max'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='diameter_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Diameter lower error (km)', null=True, verbose_name='diameter_err_min'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='dynclass',
            field=models.CharField(blank=True, default=None, help_text="(ucd=“meta.code.class;src.class”) Object's dynamical subclass as defined by Skybot (KBO>Resonant>12:5, MB>Inner, etc.).", max_length=24, null=True, verbose_name="Object's dynamical subclass as defined by Skybot"),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='e_dec_target',
            field=models.FloatField(blank=True, default=None, help_text="Error in target's declination", null=True, verbose_name='E_dec_target'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='e_ra_target',
            field=models.FloatField(blank=True, default=None, help_text="Error in target's right ascension", null=True, verbose_name='E_ra_target'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='epoch',
            field=models.FloatField(blank=True, default=None, help_text='Epoch of the orbit (Julian Date)', null=True, verbose_name='Epoch of the orbit'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='excentricity',
            field=models.FloatField(blank=True, default=None, help_text='Excentricity', null=True, verbose_name='Excentricity'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='g',
            field=models.FloatField(blank=True, default=None, help_text='Phase slope parameter', null=True, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='g_star',
            field=models.FloatField(default=0, help_text='Gaia g magnitude', verbose_name='Gaia g magnitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='h',
            field=models.FloatField(blank=True, default=None, help_text='Absolute magnitude', null=True, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='h_star',
            field=models.FloatField(blank=True, default=None, help_text='2MASS H magnitude', null=True, verbose_name='2MASS H magnitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='have_path_coeff',
            field=models.BooleanField(blank=True, default=False, help_text='Has path coefficients, i.e., the occultation passes over the earth;', null=True, verbose_name='Has path coefficients'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='inclination',
            field=models.FloatField(blank=True, default=None, help_text='Inclination (degres)', null=True, verbose_name='Inclination'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='instant_uncertainty',
            field=models.FloatField(blank=True, default=None, help_text='Instant of the closest approach uncertainty (seconds)', null=True, verbose_name='instant_uncertainty'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='j_star',
            field=models.FloatField(blank=True, default=None, help_text='2MASS J magnitude', null=True, verbose_name='2MASS J magnitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='k_star',
            field=models.FloatField(blank=True, default=None, help_text='2MASS K magnitude', null=True, verbose_name='2MASS K magnitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='last_obs_included',
            field=models.DateField(blank=True, default=None, help_text='Date of last observation included in orbit solution (YYYY-MM-DD format)', null=True, verbose_name='Date of last observation included'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='long_asc_node',
            field=models.FloatField(blank=True, default=None, help_text='Longitude of the ascending node, J2000.0 (degrees)', null=True, verbose_name='Longitude of the ascending node'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='magnitude_drop',
            field=models.FloatField(blank=True, default=None, help_text="Expected star's magnitude drop", null=True, verbose_name='magnitude_drop'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mass',
            field=models.FloatField(blank=True, default=None, help_text='Mass (kg)', null=True, verbose_name='mass'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mass_err_max',
            field=models.FloatField(blank=True, default=None, help_text='Mass lower error (kg)', null=True, verbose_name='mass_err_max'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mass_err_min',
            field=models.FloatField(blank=True, default=None, help_text='Mass upper error (kg)', null=True, verbose_name='mass_err_min'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mean_anomaly',
            field=models.FloatField(blank=True, default=None, help_text='Mean anomaly at the epoch (degrees)', null=True, verbose_name='Mean anomaly'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mean_daily_motion',
            field=models.FloatField(blank=True, default=None, help_text='Mean daily motion (degrees/day)', null=True, verbose_name='Mean daily motion'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='mpc_critical_list',
            field=models.BooleanField(blank=True, default=False, help_text='Critical objects numbered on the MPC list are those whose orbits require improvement', null=True, verbose_name='mpc_critical_list'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_coeff',
            field=models.JSONField(blank=True, default=dict, help_text='Occultation path coefficients of the polynomial fit', null=True, verbose_name='Occultation path coefficients'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_is_nightside',
            field=models.BooleanField(blank=True, default=None, help_text='True if any part of the path crosses the nightside of the Earth', null=True, verbose_name='Occultation path nightside'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_max_latitude',
            field=models.FloatField(blank=True, default=None, help_text='Maximum latitude the occultation path reaches. -180 +180', null=True, verbose_name='Maximum latitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_max_longitude',
            field=models.FloatField(blank=True, default=None, help_text='Maximum longitude the occultation path reaches. -90 +90', null=True, verbose_name='Maximum longitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_min_latitude',
            field=models.FloatField(blank=True, default=None, help_text='Minimum latitude the occultation path reaches. -180 +180', null=True, verbose_name='Minimum latitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='occ_path_min_longitude',
            field=models.FloatField(blank=True, default=None, help_text='Minimum longitude the occultation path reaches. -90 +90', null=True, verbose_name='Minimum longitude'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='perihelion',
            field=models.FloatField(blank=True, default=None, help_text='Perihelion (AU)', null=True, verbose_name='Perihelion'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='perihelion_dist',
            field=models.FloatField(blank=True, default=None, help_text='Perihelion distance (AU)', null=True, verbose_name='Perihelion distance'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='pmdec',
            field=models.FloatField(blank=True, default=0, help_text="Star's proper motion in declination (mas/yr); (0 when not provided by Gaia DR1)", null=True, verbose_name='pmdec'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='pmra',
            field=models.FloatField(blank=True, default=0, help_text='Star proper motion in right ascension (mas/yr); (0 when not provided by Gaia DR1)', null=True, verbose_name='pmra'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='position_angle',
            field=models.FloatField(default=0, help_text='Planet position angle with respect to star at C/A (degrees)', verbose_name='Position Angle'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='predict_step',
            field=models.IntegerField(blank=True, default=600, help_text='Prediction step size (seconds)', null=True, verbose_name='Prediction Step'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='principal_designation',
            field=models.CharField(blank=True, default=None, help_text='Principal designation assigned by the International Astronomical Union (IAU)', max_length=35, null=True, verbose_name='Principal Designation'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='proper_motion',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('no', 'no')], default=None, help_text='Is proper motion applied? (ok, no)', max_length=2, null=True, verbose_name='Proper Motion'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_star_candidate',
            field=models.CharField(help_text='Star candidate right ascension (hh:mm:ss)', max_length=20, verbose_name='RA Star Candidate'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_star_deg',
            field=models.FloatField(blank=True, help_text="Star's right ascension (degrees)", null=True, verbose_name='RA Star deg'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_star_to_date',
            field=models.CharField(blank=True, default=None, help_text="Star's right ascension reduced to date", max_length=35, null=True, verbose_name='ra_star_to_date'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_star_with_pm',
            field=models.CharField(blank=True, default=None, help_text="Star's right ascension corrected for proper motion", max_length=35, null=True, verbose_name='ra_star_with_pm'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_target',
            field=models.CharField(help_text="Target's right ascension (hh:mm:ss)", max_length=20, verbose_name='RA Target'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_target_apparent',
            field=models.CharField(blank=True, help_text="Target's apparent right ascension", max_length=20, null=True, verbose_name='ra_target_apparent'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='ra_target_deg',
            field=models.FloatField(blank=True, help_text="Target's right ascension (degrees)", null=True, verbose_name='RA Target deg'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='rms',
            field=models.FloatField(blank=True, default=None, help_text='r.m.s. residual of the fit (arcsec)', null=True, verbose_name='r.m.s. residual'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='semimajor_axis',
            field=models.FloatField(blank=True, default=None, help_text='Semimajor axis (AU)', null=True, verbose_name='Semimajor axis'),
        ),
        migrations.AlterField(
            model_name='occultation',
            name='velocity',
            field=models.FloatField(default=0, help_text='Velocity in plane of sky (km/s), positive= prograde, negative= retrograde', verbose_name='Velocity'),
        ),
    ]
