# Generated by Django 3.2.18 on 2024-02-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0060_auto_20240206_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asteroid",
            name="excentricity",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="excentricity",
        ),
        migrations.AddField(
            model_name="asteroid",
            name="eccentricity",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Eccentricity",
                null=True,
                verbose_name="Eccentricity",
            ),
        ),
    ]
