# Generated by Django 3.2.18 on 2024-02-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tno", "0061_auto_20240215_2052"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asteroid",
            old_name="aphelion_dist",
            new_name="aphelion",
        ),
        migrations.RenameField(
            model_name="asteroid",
            old_name="perihelion_dist",
            new_name="perihelion",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="aphelion_dist",
        ),
        migrations.RemoveField(
            model_name="occultation",
            name="perihelion_dist",
        ),
    ]
