# Generated by Django 2.2.13 on 2021-07-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0002_auto_20210713_1740'),
        ('praia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='astrometryinput',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='astrometryinput',
            name='asteroid',
        ),
        migrations.RemoveField(
            model_name='astrometryjob',
            name='asteroid',
        ),
        migrations.RemoveField(
            model_name='astrometryjob',
            name='astrometry_run',
        ),
        migrations.RemoveField(
            model_name='astrometryoutput',
            name='asteroid',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='run',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='run',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='run',
            name='input_list',
        ),
        migrations.RemoveField(
            model_name='run',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='run',
            name='proccess',
        ),
        migrations.DeleteModel(
            name='AstrometryAsteroid',
        ),
        migrations.DeleteModel(
            name='AstrometryInput',
        ),
        migrations.DeleteModel(
            name='AstrometryJob',
        ),
        migrations.DeleteModel(
            name='AstrometryOutput',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
