"""
Django settings for coreAdmin project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import urllib.parse

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Diretorio com scripts externos.
BIN_DIR = os.path.join(BASE_DIR, "bin")

# PROJECT PATHS
# estes diretorios estao montados no container utilizando variaveis de ambiente, mas para o container sempre vao ser
# os mesmos listados aqui.
LOG_DIR = "/log"
LOGGING_LEVEL = "INFO"
ARCHIVE_DIR = "/archive"
PROCCESS_DIR = "/proccess"
DES_CCD_CATALOGS_DIR = "/archive/des/public/catalogs/"

# Sub diretorios que ficam dentro de /archive

SKYBOT_ROOT = "skybot_output"
SKYBOT_OUTPUT = os.path.join(ARCHIVE_DIR, SKYBOT_ROOT)
if not os.path.exists(SKYBOT_OUTPUT):
    os.mkdir(SKYBOT_OUTPUT)

# JHONSTONS_ARCHIVE_ROOT = "jhonstons_archive"
# JHONSTONS_ARCHIVE = os.path.join(ARCHIVE_DIR, JHONSTONS_ARCHIVE_ROOT)
# if not os.path.exists(JHONSTONS_ARCHIVE):
#     os.mkdir(JHONSTONS_ARCHIVE)

MEDIA_ROOT = ARCHIVE_DIR
MEDIA_URL = "/media/"

MEDIA_TMP_DIR = os.path.join(MEDIA_ROOT, "tmp")
if not os.path.exists(MEDIA_TMP_DIR):
    os.mkdir(MEDIA_TMP_DIR)

MEDIA_TMP_URL = urllib.parse.urljoin(MEDIA_URL, "tmp/")

DATA_URL = "/data/"
DATA_TMP_DIR = MEDIA_TMP_DIR
DATA_TMP_URL = urllib.parse.urljoin(DATA_URL, "tmp/")

ENVIRONMENT_NAME = os.environ.get("ENVIRONMENT_NAME", "Development")

# Emails
# Notifications Email
EMAIL_NOTIFICATION = os.environ.get("EMAIL_NOTIFICATION", "sso-portal@linea.gov.br")


EMAIL_HELPDESK = os.environ.get("EMAIL_HELPDESK", "helpdesk@linea.gov.br")

EMAIL_NOTIFICATION_COPY_TO = list(
    [os.environ.get("EMAIL_NOTIFICATION", "sso-portal@linea.gov.br")]
)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.linea.org.br"
EMAIL_PORT = 587
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""


APPLICATION_NAME = "SSSO - Solar System Small Object"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "m=5=08^4a(il)bba)$cd%f*#wrcammi(r(q#($b$n^-jz8%+j0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "url_filter",
    "corsheaders",
    "shibboleth",
    # Project Apps
    "common",
    "tno",
    "skybot",
    "des",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "common.shibboleth.ShibbolethMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "current_user.CurrentUserMiddleware",
]

ROOT_URLCONF = "coreAdmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_settings_export.settings_export",
            ],
        },
    },
]

STATICFILES_DIRS = (os.path.join(BASE_DIR, "staticfiles"),)

WSGI_APPLICATION = "coreAdmin.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "tno_admin",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "database",
        "PORT": 5432,
        # caso o banco de dados tenha definido um schema
        # "OPTIONS": {"options": "-c search_path=<DB_SCHEMA>,public"},
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/django_static/"
STATIC_ROOT = os.path.join(BASE_DIR, "django_static")

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

# https://docs.djangoproject.com/en/4.1/ref/settings/#csrf-cookie-name
CSRF_COOKIE_NAME = "tno.csrftoken"

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = "/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "common.pagination.StandardResultsSetPagination",
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": (
        # "url_filter.integrations.drf.DjangoFilterBackend",
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    # https://www.django-rest-framework.org/api-guide/relations/#select-field-cutoffs
    "HTML_SELECT_CUTOFF": 50
}

# CORS com essa combinação o serv de desenvolvimento do frontend consegue se authenticar
if DEBUG:
    ALLOWED_HOSTS = "*"
    CORS_ALLOW_CREDENTIALS = True
    SESSION_COOKIE_SAMESITE = None


# TODO: Talves nao esteja mais sendo utilizado
# Url para download dos CCDs,
# usar None para desativar esta opcao.
# ex: 'https://desar2.cosmology.illinois.edu/DESFiles/desarchive/'
DES_ARCHIVE_URL = os.getenv("DES_ARCHIVE_URL")
if DES_ARCHIVE_URL is not None:
    try:
        # Username e Password no DES.
        DES_USERNAME = os.getenv("DES_USERNAME")
        DES_PASSWORD = os.getenv("DES_PASSWORD")
    except Exception as e:
        raise Exception("DES user settings are required in .env file")


# Skybot Server
# Url para o serviço do skybot sempre com a barra no final.
# Skybot do linea: SKYBOT_SERVER=http://srvskybot.linea.org.br/webservices/skybot/
# Skybot da Franca: SKYBOT_SERVER="http://vo.imcce.fr/webservices/skybot/"
SKYBOT_SERVER = "http://vo.imcce.fr/webservices/skybot/"



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s] %(message)s"},
    },
    "handlers": {
        "file": {
            "level": LOGGING_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "django.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
        # "proccess": {
        #     "level": LOGGING_LEVEL,
        #     "class": "logging.handlers.RotatingFileHandler",
        #     "maxBytes": 1024 * 1024 * 5,  # 5 MB
        #     "backupCount": 5,
        #     "filename": os.path.join(LOG_DIR, "proccess.log"),
        #     "formatter": "standard",
        # },
        # Skybot Download
        "skybot": {
            "level": LOGGING_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "filename": os.path.join(LOG_DIR, "skybot.log"),
            "formatter": "standard",
        },
        # Skybot Load data
        "skybot_load_data": {
            "level": LOGGING_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "filename": os.path.join(LOG_DIR, "skybot_load_data.log"),
            "formatter": "standard",
        },
        "shibboleth": {
            "level": LOGGING_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "filename": os.path.join(LOG_DIR, "auth_shibboleth.log"),
            "formatter": "standard",
        },
        "asteroids": {
            "level": LOGGING_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "filename": os.path.join(LOG_DIR, "asteroids.log"),
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": LOGGING_LEVEL,
            "propagate": True,
        },
        # "proccess": {
        #     "handlers": ["proccess"],
        #     "level": LOGGING_LEVEL,
        #     "propagate": True,
        # },
        "skybot": {
            "handlers": ["skybot"],
            "level": LOGGING_LEVEL,
            "propagate": False,
        },
        "skybot_load_data": {
            "handlers": ["skybot_load_data"],
            "level": LOGGING_LEVEL,
            "propagate": False,
        },
        "shibboleth": {
            "handlers": ["shibboleth"],
            "level": LOGGING_LEVEL,
            "propagate": True,
        },
        "asteroids": {
            "handlers": ["asteroids"],
            "level": LOGGING_LEVEL,
            "propagate": True,
        },
    },
}
# Autenticacao com Shibboleth desativada por padrão
SHIBBOLETH_ENABLED = False

# Aqui é feita a importação do arquivo de variaveis locais.
# As variaveis declaradas neste arquivo sobrescrevem as variaveais declaradas antes
# deste import. isso é usado para permitir diferentes configurações por ambiente.
# basta cada ambiente ter o seu arquivo local_vars.py.
try:
    from coreAdmin.local_settings import *
except Exception:
    raise FileNotFoundError(
        "local_settings.py file not found. it is necessary that the coraAdmin/local_settings.py file exists with the specific settings of this environment."
    )

SETTINGS_EXPORT = []

# Shibboleth Authentication
if SHIBBOLETH_ENABLED is True:
    # https://github.com/Brown-University-Library/django-shibboleth-remoteuser
    SHIBBOLETH_ATTRIBUTE_MAP = {
        "eppn": (True, "username"),
        "cn": (False, "first_name"),
        "sn": (False, "last_name"),
        "Shib-inetOrgPerson-mail": (False, "email"),
    }
    SHIBBOLETH_GROUP_ATTRIBUTES = "Shibboleth"
    # Including Shibboleth authentication:
    AUTHENTICATION_BACKENDS += ("shibboleth.backends.ShibbolethRemoteUserBackend",)

    SHIBBOLETH_ENABLED = True
