site_name: LIneA Occultation Prediction Database

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

nav:
  - Overview: 'index.md'
  - Release Notes:
      - Initial Release: 'release-notes.md'
  - User Guide:
      - Filter Events: 'user-guide/filter-events.md'
      - Occultation Details Page: 'user-guide/occultation-details-page.md'
      - Occultation Predictions Table: 'user-guide/occultation-predictions-table.md'
      - API: 'user-guide/api.md'
      - Citations: 'user-guide/citations.md'
  - FAQ: 'faq.md'
  # - About: 'about.md'
