# Generated by Django 3.2.18 on 2025-09-05 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PREPARE', 'Prepare'), ('SUBMIT', 'Submit'), ('RUN', 'Run'), ('INGEST', 'Ingest')], max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('backoff_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asteroid_id', models.CharField(db_index=True, max_length=100)),
                ('priority', models.IntegerField(default=100)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY_FOR_RUN', 'Ready for Run'), ('SUBMITTING', 'Submitting'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('WAITING_RESULTS', 'Waiting Results'), ('INGESTING', 'Ingesting'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('STALLED', 'Stalled'), ('ABORTED', 'Aborted')], default='PENDING', max_length=32)),
                ('workdir', models.CharField(blank=True, max_length=1024)),
                ('input_manifest', models.JSONField(blank=True, default=dict)),
                ('output_manifest', models.JSONField(blank=True, default=dict)),
                ('slurm_job_id', models.CharField(blank=True, max_length=64)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aborted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='predictiontask',
            index=models.Index(fields=['state', 'priority', '-created_at'], name='predict_occ_state_4c131d_idx'),
        ),
        migrations.AddField(
            model_name='predictionattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='predict_occultation.predictiontask'),
        ),
    ]
