# Generated by Django 3.2.18 on 2025-09-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionattempt',
            name='backoff_until',
        ),
    ]
