# Generated by Django 3.2.18 on 2025-09-17 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0002_remove_predictionattempt_backoff_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(choices=[('PREPARE', 'Prepare'), ('SUBMIT', 'Submit'), ('INGEST', 'Ingest')], max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
