# Generated by Django 3.2.18 on 2025-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0003_workersheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersheartbeat',
            name='uptime',
            field=models.IntegerField(default=0),
        ),
    ]
