# Generated by Django 3.2.18 on 2025-10-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0004_workersheartbeat_uptime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionAttempt',
        ),
    ]
