# Generated by Django 3.2.18 on 2025-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0005_delete_predictionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersheartbeat',
            name='worker',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
