# Generated by Django 3.2.18 on 2025-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_occultation', '0006_alter_workersheartbeat_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontask',
            name='debug',
            field=models.BooleanField(default=False),
        ),
    ]
