# Generated by Django 2.0.3 on 2018-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationfile',
            name='download_url',
            field=models.URLField(blank=True, help_text='Url used to download file.', null=True, verbose_name='Download URL'),
        ),
        migrations.AddField(
            model_name='orbitalparameterfile',
            name='download_url',
            field=models.URLField(blank=True, help_text='Url used to download file.', null=True, verbose_name='Download URL'),
        ),
    ]
