# Generated by Django 2.0.12 on 2019-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('warning', 'Warning'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed'), ('idle', 'Idle')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
    ]
