# Generated by Django 2.0.3 on 2018-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='BspJplFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, unique=True, verbose_name='Name')),
                ('filename', models.CharField(blank=True, help_text='Filename is formed by name without space and separated by underline.', max_length=256, null=True, verbose_name='Filename')),
                ('download_start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Download Start')),
                ('download_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Download finish')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
            ],
        ),
        migrations.AlterField(
            model_name='observationfile',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename is formed by name without space and separated by underline.', max_length=256, null=True, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='orbitalparameterfile',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename is formed by name without space and separated by underline.', max_length=256, null=True, verbose_name='Filename'),
        ),
    ]
