# Generated by Django 2.0.3 on 2018-07-17 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tno', '0038_auto_20180717_1330'),
        ('praia', '0007_run_proccess'),
        ('orbit', '0004_auto_20180717_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Run',
            new_name='OrbitRun',
        ),
    ]
