# Generated by Django 2.0.3 on 2018-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0006_orbitrun_relative_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitrun',
            name='average_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Time'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='count_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were executed by NIMA.', null=True, verbose_name='Num Executed Objects'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='count_failed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of failed objects', null=True, verbose_name='Count Failed'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed by NIMA.', null=True, verbose_name='Num Not Executed Objects'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='count_objects',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects received as input', null=True, verbose_name='Num Objects'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='count_success',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects successfully executed', null=True, verbose_name='Count Success'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
    ]
