# Generated by Django 2.0.3 on 2018-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0007_auto_20180808_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitrun',
            name='execution_download_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Download Time'),
        ),
        migrations.AddField(
            model_name='orbitrun',
            name='execution_nima_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution NIMA Time'),
        ),
    ]
