# Generated by Django 2.0.3 on 2018-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0008_auto_20180809_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, unique=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=6, null=True, verbose_name='Number')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10, null=True, verbose_name='Status')),
                ('error_msg', models.CharField(blank=True, help_text='When the status is failure, this field should contain a message with the error.', max_length=256, null=True, verbose_name='Error Message')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to the refine orbit OBJECT directory, this is the internal path in the proccess directory.', max_length=256, null=True, verbose_name='Relative Path')),
                ('absolute_path', models.CharField(blank=True, help_text='Absolute Path to refine orbit OBJECT directory.', max_length=1024, null=True, verbose_name='Absolute Path')),
            ],
        ),
    ]
