# Generated by Django 2.0.3 on 2018-08-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0009_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='RefinedObject',
        ),
    ]
