# Generated by Django 2.0.3 on 2018-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0010_auto_20180809_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefinedObject',
            new_name='Asteroid',
        ),
    ]
