# Generated by Django 2.0.3 on 2018-08-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0012_auto_20180809_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinedOrbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Filename is formed by name without space and separated by underline.', max_length=256, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(help_text='File Size in bytes', verbose_name='File Size')),
                ('file_type', models.CharField(help_text="File extension like '.txt'", max_length=10, verbose_name='File Type')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='Relative Path')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asteroid', to='orbit.RefinedAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
