# Generated by Django 2.0.3 on 2018-08-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0013_refinedorbit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refinedorbit',
            old_name='obj',
            new_name='asteroid',
        ),
    ]
