# Generated by Django 2.0.3 on 2018-08-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0014_auto_20180809_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinedasteroid',
            name='input_praia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orbit_run', to='orbit.OrbitRun', verbose_name='Orbit Run'),
        ),
    ]
