# Generated by Django 2.0.3 on 2018-08-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0015_refinedasteroid_input_praia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refinedasteroid',
            old_name='input_praia',
            new_name='orbit_run',
        ),
    ]
