# Generated by Django 2.0.3 on 2018-08-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0016_auto_20180809_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedorbit',
            name='asteroid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refined_orbit', to='orbit.RefinedAsteroid', verbose_name='Asteroid'),
        ),
    ]
