# Generated by Django 2.0.3 on 2018-08-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0017_auto_20180815_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
