# Generated by Django 2.0.3 on 2018-08-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0018_auto_20180816_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinedOrbitInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('observations', 'Observations'), ('orbital_parameters', 'Orbital Parameters'), ('bsp_jpl', 'BSP JPL'), ('astrometry', 'Astrometry')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type')),
                ('source', models.CharField(choices=[('MPC', 'MPC'), ('AstDys', 'AstDys'), ('JPL', 'JPL')], max_length=6, verbose_name='Source')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
                ('filename', models.CharField(max_length=256, verbose_name='Filename')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='Relative Path')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='orbit.RefinedAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
