# Generated by Django 2.0.3 on 2018-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0019_refinedorbitinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedorbitinput',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Time'),
        ),
    ]
