# Generated by Django 2.0.3 on 2018-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0020_auto_20180816_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedorbitinput',
            name='source',
            field=models.CharField(blank=True, choices=[('MPC', 'MPC'), ('AstDys', 'AstDys'), ('JPL', 'JPL')], max_length=6, null=True, verbose_name='Source'),
        ),
    ]
