# Generated by Django 2.0.3 on 2018-08-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0021_auto_20180820_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedasteroid',
            name='name',
            field=models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, verbose_name='Name'),
        ),
    ]
