# Generated by Django 2.0.3 on 2018-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0022_auto_20180821_1232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refinedasteroid',
            unique_together={('orbit_run', 'name')},
        ),
    ]
