# Generated by Django 2.0.3 on 2018-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0023_auto_20180821_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitrun',
            name='count_warning',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects with status warning', null=True, verbose_name='Count Warning'),
        ),
    ]
