# Generated by Django 2.0.3 on 2018-08-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0024_orbitrun_count_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedasteroid',
            name='orbit_run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asteroids', to='orbit.OrbitRun', verbose_name='Orbit Run'),
        ),
    ]
