# Generated by Django 2.0.3 on 2018-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0025_auto_20180821_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinedorbit',
            name='type',
            field=models.CharField(blank=True, choices=[('residual_all_v1', 'Residual All v1'), ('residual_all_v2', 'Residual All v2'), ('residual_recent', 'Residual Recent'), ('comparison_nima_jpl_ra', 'Comparison NIMA jpl RA'), ('comparison_nima_jpl_dec', 'Comparison NIMA jpl Dec'), ('comparison_bsp_integration', 'Comparison bsp integration')], default=None, help_text='Description of the result type.', max_length=60, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='orbitrun',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
