# Generated by Django 2.0.3 on 2018-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0026_auto_20181123_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='refinedorbit',
            name='type',
            field=models.CharField(blank=True, choices=[('bsp_nima', 'BSP NIMA'), ('residual_all_v1', 'Residual All v1'), ('residual_all_v2', 'Residual All v2'), ('residual_recent', 'Residual Recent'), ('comparison_nima_jpl_ra', 'Comparison NIMA jpl RA'), ('comparison_nima_jpl_dec', 'Comparison NIMA jpl Dec'), ('comparison_bsp_integration', 'Comparison bsp integration'), ('correl_mat', 'correl.mat'), ('sigyr_res', 'sigyr.res'), ('offset_oth_obs', 'offset_oth.obs'), ('ci_ast_dat', 'CI_ast.dat'), ('offset_oth_dat', 'offset_oth.dat'), ('ephemni_res', 'ephemni.res'), ('omc_ast_res', 'omc_ast.res'), ('ephembsp_res', 'ephembsp.res'), ('cov_mat', 'cov.mat')], default=None, help_text='Description of the result type.', max_length=60, null=True, verbose_name='Type'),
        ),
    ]
