# Generated by Django 2.0.3 on 2019-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
    ]
