# Generated by Django 2.0.3 on 2018-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointings',
            name='downloaded',
            field=models.BooleanField(default=False, help_text='flag indicating whether the image was downloaded from DES.', verbose_name='Downloaded'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['expnum'], name='tno_pointin_expnum_00bcc0_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['expnum', 'ccdnum', 'band'], name='tno_pointin_expnum_ff21b4_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['date_obs'], name='tno_pointin_date_ob_27847b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['rac1'], name='tno_pointin_rac1_9224e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['rac2'], name='tno_pointin_rac2_f9c599_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['rac3'], name='tno_pointin_rac3_d1d4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['rac4'], name='tno_pointin_rac4_7405b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['decc1'], name='tno_pointin_decc1_569be8_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['decc2'], name='tno_pointin_decc2_53842b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['decc3'], name='tno_pointin_decc3_c833a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['decc4'], name='tno_pointin_decc4_564aec_idx'),
        ),
    ]
