# Generated by Django 2.2.13 on 2021-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, unique=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=35, null=True, verbose_name='Number')),
                ('base_dynclass', models.CharField(db_index=True, help_text='(ucd=“meta.code.class”) Base Object class (TNO, Centaur, Trojan, etc.).', max_length=24, verbose_name='Base Object classification')),
                ('dynclass', models.CharField(db_index=True, help_text='(ucd=“meta.code.class;src.class”) Object class (TNO, Centaur, Trojan, etc.).', max_length=24, verbose_name='Object classification')),
            ],
        ),
    ]
