# Generated by Django 2.0.3 on 2019-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0002_skybotrun_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
    ]
