# Generated by Django 2.0.3 on 2018-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0002_auto_20180411_1854'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pointings',
            index=models.Index(fields=['expnum', 'ccdnum'], name='tno_pointin_expnum_7f7694_idx'),
        ),
    ]
