# Generated by Django 2.0.3 on 2019-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0003_skybotrun_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='rows',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Rows'),
        ),
    ]
