# Generated by Django 2.0.3 on 2018-04-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0003_auto_20180411_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointings',
            name='cloud_apass',
            field=models.FloatField(help_text='Atmospheric extinction in magnitudes', verbose_name='Cloud apass'),
        ),
        migrations.AlterField(
            model_name='pointings',
            name='cloud_nomad',
            field=models.FloatField(help_text='Atmospheric extinction in magnitudes', verbose_name='Cloud nomad'),
        ),
        migrations.AlterField(
            model_name='pointings',
            name='compression',
            field=models.CharField(help_text='Compression format (.fz) used in FITS files', max_length=5, verbose_name='Compression'),
        ),
        migrations.AlterField(
            model_name='pointings',
            name='filename',
            field=models.CharField(help_text='Name of FITS file with a CCD image.', max_length=256, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='pointings',
            name='t_eff',
            field=models.FloatField(help_text='Parameter related to image quality', verbose_name='t_eff'),
        ),
    ]
