# Generated by Django 2.0.3 on 2019-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0004_skybotrun_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotrun',
            name='date_final',
            field=models.DateField(blank=True, null=True, verbose_name='Date Final'),
        ),
        migrations.AlterField(
            model_name='skybotrun',
            name='date_initial',
            field=models.DateField(blank=True, null=True, verbose_name='Date Initial'),
        ),
        migrations.AlterField(
            model_name='skybotrun',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed'), ('canceled', 'Canceled')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
    ]
