# Generated by Django 2.0.3 on 2019-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0005_auto_20190416_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdimage',
            name='download_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Download time'),
        ),
    ]
