# Generated by Django 2.2.13 on 2021-10-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0005_occultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occultation',
            name='name',
            field=models.CharField(db_index=True, help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, verbose_name='Name'),
        ),
    ]
