# Generated by Django 2.0.3 on 2018-04-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0005_auto_20180412_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desfile_id', models.BigIntegerField(help_text='Unique identifier for each CCD.', verbose_name='CCD Id')),
                ('filename', models.CharField(help_text='Name of FITS file with a CCD image.', max_length=256, verbose_name='Filename')),
                ('download_start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Download Start')),
                ('download_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Download finish')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
                ('pointing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tno.Pointings', verbose_name='Pointing')),
            ],
        ),
    ]
