# Generated by Django 2.0.3 on 2019-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0006_ccdimage_download_time'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_rac1_0866c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_rac2_d56a32_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_rac3_ab0355_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_rac4_41f39a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_decc1_7e9786_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_decc2_f695e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_decc3_e56097_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_decc4_91f279_idx',
        ),
        migrations.AddIndex(
            model_name='pointing',
            index=models.Index(fields=['pfw_attempt_id'], name='tno_pointin_pfw_att_be9751_idx'),
        ),
        migrations.AddIndex(
            model_name='pointing',
            index=models.Index(fields=['desfile_id'], name='tno_pointin_desfile_ebd259_idx'),
        ),
        migrations.AddIndex(
            model_name='pointing',
            index=models.Index(fields=['filename'], name='tno_pointin_filenam_7a0763_idx'),
        ),
    ]
