# Generated by Django 2.0.3 on 2018-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0007_auto_20180416_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointing',
            name='dec_size',
            field=models.DecimalField(decimal_places=7, help_text='CCD dimensions in degrees (width × height).', max_digits=10, verbose_name='dec_size'),
        ),
        migrations.AlterField(
            model_name='pointing',
            name='ra_size',
            field=models.DecimalField(decimal_places=7, help_text='CCD dimensions in degrees (width × height).', max_digits=10, verbose_name='ra_size'),
        ),
    ]
