# Generated by Django 2.0.12 on 2020-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0007_auto_20191016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotoutput',
            name='d',
            field=models.FloatField(blank=True, default=None, help_text='(ucd="pos.ang") Body-to-center angular distance', null=True, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='ddec',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“pos.pm;pos.eq.dec”) Motion in declination d(DEC)', null=True, verbose_name='dDEC'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='dgeo',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“phys.distance”) Distance from observer', null=True, verbose_name='Dgeo'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='dhelio',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“phys.distance”) Distance from the Sun', null=True, verbose_name='Dhelio'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='dracosdec',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“pos.pm;pos.eq.ra”) Motion in right ascension d(RA)cos(DEC)', null=True, verbose_name='dRAcosDec'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='errpos',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“stat.error.sys”) Uncertainty on the (RA,DEC) coordinates', null=True, verbose_name='ErrPos'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='externallink',
            field=models.URLField(blank=True, default=None, help_text='(ucd=“meta.ref.url”) External link to hint the target', null=True, verbose_name='ExternalLink'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='jdref',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“time.epoch”) Reference epoch of the position/velocity vector', null=True, verbose_name='JDRef'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='mv',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“phot.mag;em.opt.V”) Visual magnitude', null=True, verbose_name='Mv'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='num',
            field=models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=6, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='phase',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“pos.phaseAng”) Phase angle, e.g. elongation of earth from sun as seen from object', null=True, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='px',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.orbital.pos;meta.id.x”) Mean J2000 heliocentric position vector, x component', null=True, verbose_name='Px'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='py',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.orbital.pos;meta.id.y”) Mean J2000 heliocentric position vector, y component', null=True, verbose_name='Py'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='pz',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.orbital.pos;meta.id.z”) Mean J2000 heliocentric position vector, z component', null=True, verbose_name='Pz'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='solelong',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“pos.angDistance”) Solar elongation, e.g. elongation of object from sun as seen from Earth', null=True, verbose_name='SolElong'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='vx',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.veloc.orbital;meta.id.x”) Mean J2000 heliocentric velocity vector, x component', null=True, verbose_name='Vx'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='vy',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.veloc.orbital;meta.id.y”) Mean J2000 heliocentric velocity vector, y component', null=True, verbose_name='Vy'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='vz',
            field=models.FloatField(blank=True, default=None, help_text='(ucd=“src.veloc.orbital;meta.id.z”) Mean J2000 heliocentric velocity vector, z component', null=True, verbose_name='Vz'),
        ),
    ]
