# Generated by Django 2.0.3 on 2018-04-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0008_auto_20180417_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdimage',
            name='pointing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tno.Pointing', verbose_name='Pointing'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='pointing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tno.Pointing', verbose_name='Pointing'),
        ),
        migrations.DeleteModel(
            name='Pointings',
        ),
    ]
