# Generated by Django 2.0.3 on 2018-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0009_auto_20180417_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotoutput',
            name='dec',
            field=models.CharField(help_text='(ucd=“pos.eq.dec;meta.main”) Declination of the identified object.', max_length=20, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='ra',
            field=models.CharField(help_text='(ucd=“pos.eq.ra;meta.main”) Right ascension of the identified object.', max_length=20, verbose_name='RA'),
        ),
    ]
