# Generated by Django 2.0.12 on 2020-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0009_auto_20200428_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotoutput',
            name='num',
            field=models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=35, null=True, verbose_name='Number'),
        ),
    ]
