# Generated by Django 2.0.3 on 2018-04-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0010_auto_20180417_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotoutput',
            name='pointing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Pointing', verbose_name='Pointing'),
        ),
    ]
