# Generated by Django 2.0.12 on 2020-04-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0010_auto_20200428_1929'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skybotoutput',
            name='tno_skyboto_expnum_08cde1_idx',
        ),
        migrations.RemoveIndex(
            model_name='skybotoutput',
            name='tno_skyboto_expnum_fd6537_idx',
        ),
        migrations.RemoveIndex(
            model_name='skybotoutput',
            name='tno_skyboto_expnum_a7ca7e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='skybotoutput',
            unique_together={('name', 'raj2000', 'decj2000')},
        ),
    ]
