# Generated by Django 2.0.3 on 2018-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0011_auto_20180417_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotoutput',
            name='band',
            field=models.CharField(blank=True, choices=[('u', 'u'), ('g', 'g'), ('r', 'r'), ('i', 'i'), ('z', 'z'), ('Y', 'Y')], default=None, help_text='Filter used to do the observation (u, g, r, i, z, Y).', max_length=1, null=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='ccdnum',
            field=models.IntegerField(blank=True, default=None, help_text='CCD Number (1, 2, ..., 62)', null=True, verbose_name='CCD'),
        ),
        migrations.AlterField(
            model_name='skybotoutput',
            name='expnum',
            field=models.BigIntegerField(blank=True, default=None, help_text='Unique identifier for each image, same function as pfw_attenp_id (it also recorded in the file name)', null=True, verbose_name='Exposure'),
        ),
    ]
