# Generated by Django 2.0.3 on 2018-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0012_auto_20180417_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdimage',
            name='desfile_id',
            field=models.BigIntegerField(blank=True, default=None, help_text='Unique identifier for each CCD.', null=True, verbose_name='CCD Id'),
        ),
        migrations.AlterField(
            model_name='ccdimage',
            name='pointing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Pointing', verbose_name='Pointing'),
        ),
    ]
