# Generated by Django 2.0.12 on 2020-04-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0012_auto_20200429_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skybotoutput',
            name='pointing',
        ),
    ]
