# Generated by Django 2.0.3 on 2018-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0013_auto_20180417_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(help_text='List name', max_length=128, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('database', models.CharField(blank=True, help_text='Database identifier in settings', max_length=128, null=True, verbose_name='Database')),
                ('schema', models.CharField(blank=True, max_length=128, null=True, verbose_name='Schema name')),
                ('tablename', models.CharField(help_text='Tablename without schema', max_length=128, verbose_name='Tablename')),
                ('rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of rows')),
                ('columns', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of columns')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size in bytes')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('sql', models.TextField(blank=True, help_text='SQL for the table contents to be created', null=True, verbose_name='SQL')),
                ('sql_creation', models.TextField(blank=True, help_text='Sql used in table creation', null=True, verbose_name='SQL Creation')),
            ],
        ),
    ]
