# Generated by Django 2.0.12 on 2020-04-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0014_skybotoutput_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skybotoutput',
            unique_together={('name', 'raj2000', 'decj2000', 'ticket')},
        ),
    ]
