# Generated by Django 2.0.3 on 2018-05-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0014_customlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='filter_diffdatenights',
            field=models.FloatField(blank=True, help_text='Filter by minimun difference time between observations', null=True, verbose_name='Filter diff nights'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='filter_dynclass',
            field=models.CharField(blank=True, help_text='Filter by Object class (TNO, Centaur, Trojan, etc.).', max_length=256, null=True, verbose_name='Filter Classification'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='filter_magnitude',
            field=models.FloatField(blank=True, help_text='Filter by Object Magnitude', null=True, verbose_name='Filter Magnitude'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='filter_morefilter',
            field=models.BooleanField(default=False, help_text='Filter by objects with more than one filter in the some night', verbose_name='Filter more Bands'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='filter_name',
            field=models.CharField(blank=True, help_text='Filter By Object name.', max_length=32, null=True, verbose_name='Filter Name'),
        ),
    ]
