# Generated by Django 2.0.12 on 2020-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0015_auto_20200429_1929'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skybotoutput',
            name='tno_skyboto_raj2000_496076_idx',
        ),
        migrations.RemoveIndex(
            model_name='skybotoutput',
            name='tno_skyboto_decj200_2adde4_idx',
        ),
        migrations.AddIndex(
            model_name='skybotoutput',
            index=models.Index(fields=['ticket'], name='tno_skyboto_ticket_981da2_idx'),
        ),
    ]
