# Generated by Django 2.0.3 on 2018-05-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0015_auto_20180521_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='creation_time',
            field=models.IntegerField(blank=True, help_text='Creation Time in seconds', null=True, verbose_name='Creation Time'),
        ),
    ]
