# Generated by Django 2.0.12 on 2020-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0016_auto_20200429_2007'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_expnum_807fae_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_expnum_f5e2aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointing',
            name='tno_pointin_expnum_56b427_idx',
        ),
        migrations.AlterField(
            model_name='pointing',
            name='desfile_id',
            field=models.BigIntegerField(help_text='Unique identifier for each CCD.', unique=True, verbose_name='CCD Id'),
        ),
        migrations.AlterField(
            model_name='pointing',
            name='expnum',
            field=models.BigIntegerField(help_text='identifier for each image.', verbose_name='Expnum'),
        ),
        migrations.AlterField(
            model_name='pointing',
            name='pfw_attempt_id',
            field=models.BigIntegerField(help_text='Unique identifier for each image (1 image is composed by 62 CCDs)', verbose_name='Exposure Id'),
        ),
    ]
