# Generated by Django 2.0.12 on 2020-06-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0017_auto_20200504_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccdimage',
            name='pointing',
        ),
        migrations.DeleteModel(
            name='CcdImage',
        ),
    ]
