# Generated by Django 2.0.3 on 2018-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0017_auto_20180521_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='n_columns',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of columns'),
        ),
        migrations.AlterField(
            model_name='customlist',
            name='columns',
            field=models.CharField(blank=True, help_text='Column names separated by comma.', max_length=1024, null=True, verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='customlist',
            name='schema',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Schema'),
        ),
    ]
