# Generated by Django 2.0.12 on 2020-06-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0018_auto_20200603_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skybotrun',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SkybotRun',
        ),
    ]
