# Generated by Django 2.0.3 on 2018-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0018_auto_20180521_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlist',
            name='creation_time',
            field=models.FloatField(blank=True, help_text='Creation Time in seconds', null=True, verbose_name='Creation Time'),
        ),
    ]
