# Generated by Django 2.0.3 on 2018-05-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0019_auto_20180521_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='error_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
