# Generated by Django 2.0.12 on 2020-06-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0019_auto_20200603_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkybotOutput',
        ),
    ]
