# Generated by Django 2.0.12 on 2020-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0020_delete_skybotoutput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pointing',
        ),
    ]
