# Generated by Django 2.0.3 on 2018-05-22 00:29

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tno', '0020_auto_20180521_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
