# Generated by Django 2.0.3 on 2018-05-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0021_customlist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlist',
            name='owner',
        ),
    ]
