# Generated by Django 2.0.3 on 2018-06-12 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tno', '0024_process'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Process',
            new_name='Proccess',
        ),
    ]
