# Generated by Django 2.0.3 on 2018-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0025_auto_20180612_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='proccess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
