# Generated by Django 2.0.3 on 2018-06-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0026_proccess_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('table', 'Table'), ('fits', 'Fits'), ('image', 'Image')], max_length=10, null=True, verbose_name='Type')),
                ('database', models.CharField(blank=True, help_text='Database identifier in settings', max_length=128, null=True, verbose_name='Database')),
                ('schema', models.CharField(blank=True, max_length=128, null=True, verbose_name='Schema')),
                ('tablename', models.CharField(blank=True, help_text='Tablename without schema', max_length=128, null=True, verbose_name='Tablename')),
                ('rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of rows')),
                ('filename', models.CharField(blank=True, help_text='Name of FITS file with a CCD image.', max_length=256, null=True, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
                ('proccess', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Proccess', verbose_name='Proccess')),
            ],
        ),
    ]
