# Generated by Django 2.0.3 on 2018-06-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0002_auto_20180612_1629'),
        ('tno', '0027_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='proccess',
            name='praia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='praia.Run', verbose_name='PRAIA'),
        ),
    ]
