# Generated by Django 2.0.3 on 2018-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0028_proccess_praia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, unique=True, verbose_name='Name')),
                ('source', models.CharField(choices=[('MPC', 'MPC'), ('AstDys', 'AstDys')], max_length=6, verbose_name='Source')),
                ('observations', models.PositiveIntegerField(help_text='Number of Observations for this object or number of lines in the file.', verbose_name='Observations')),
                ('filename', models.CharField(help_text='Name of FITS file with a CCD image.', max_length=256, verbose_name='Filename')),
                ('download_start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Download Start')),
                ('download_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Download finish')),
                ('download_time', models.FloatField(blank=True, null=True, verbose_name='Download Time')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
            ],
        ),
    ]
