# Generated by Django 2.0.3 on 2018-06-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0029_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='download_time',
        ),
    ]
