# Generated by Django 2.0.3 on 2018-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0030_remove_observation_download_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='external_url',
            field=models.URLField(blank=True, help_text='File Url in the original service.', null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of FITS file with a CCD image.', max_length=256, null=True, verbose_name='Filename'),
        ),
    ]
