# Generated by Django 2.0.3 on 2018-06-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0031_auto_20180625_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observations',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Observations for this object or number of lines in the file.', null=True, verbose_name='Observations'),
        ),
    ]
