# Generated by Django 2.0.3 on 2018-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0032_auto_20180625_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, unique=True, verbose_name='Name')),
                ('source', models.CharField(choices=[('MPC', 'MPC'), ('AstDys', 'AstDys')], max_length=6, verbose_name='Source')),
                ('filename', models.CharField(blank=True, help_text='Name of FITS file with a CCD image.', max_length=256, null=True, verbose_name='Filename')),
                ('download_start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Download Start')),
                ('download_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Download finish')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
                ('external_url', models.URLField(blank=True, help_text='File Url in the original service.', null=True, verbose_name='External URL')),
            ],
        ),
    ]
