# Generated by Django 2.0.3 on 2018-07-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0033_orbitalparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proccess',
            name='praia',
        ),
    ]
