# Generated by Django 2.0.3 on 2018-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0034_remove_proccess_praia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proccess',
            name='absolute_path',
            field=models.CharField(blank=True, help_text='Absolute path to the process directory, this is the EXTERNAL path to the container.', max_length=1024, null=True, verbose_name='Absolute Path'),
        ),
        migrations.AddField(
            model_name='proccess',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Path relative to the process directory, this is the internal path in the container.', max_length=256, null=True, verbose_name='Relative Path'),
        ),
    ]
