# Generated by Django 2.0.3 on 2018-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0035_auto_20180703_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='proccess',
            name='purged',
            field=models.BooleanField(default=False, help_text='This flag true indicates that the marked process was removed and your data excluded.', verbose_name='Purged'),
        ),
    ]
