# Generated by Django 2.0.3 on 2018-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0036_proccess_purged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlist',
            name='filter_dynclass',
            field=models.TextField(blank=True, help_text='Filter by Object class (TNO, Centaur, Trojan, etc.).', null=True, verbose_name='Filter Classification'),
        ),
    ]
