# Generated by Django 2.0.3 on 2018-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0037_auto_20180711_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='OrbitalParameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proccess',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
