# Generated by Django 2.0.3 on 2018-07-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0038_auto_20180717_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='proccess',
            name='input_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.CustomList', verbose_name='Input List'),
        ),
    ]
