# Generated by Django 2.0.3 on 2018-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0039_proccess_input_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('database', models.CharField(blank=True, help_text='Database identifier in settings', max_length=128, null=True, verbose_name='Database')),
                ('schema', models.CharField(blank=True, max_length=128, null=True, verbose_name='Schema name')),
                ('tablename', models.CharField(help_text='Tablename without schema', max_length=128, verbose_name='Tablename')),
                ('rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of rows')),
                ('num_columns', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of columns')),
                ('tbl_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size in bytes')),
            ],
        ),
    ]
