# Generated by Django 2.0.3 on 2018-09-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0040_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='num_columns',
            new_name='columns',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='tbl_size',
            new_name='size',
        ),
    ]
