# Generated by Django 2.0.3 on 2018-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0041_auto_20180903_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='dec_property',
            field=models.CharField(default='dec', help_text='name of the column that represents the Dec in degrees', max_length=128, verbose_name='Dec Property'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Internal Name'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='ra_property',
            field=models.CharField(default='ra', help_text='name of the column that represents the RA in degrees', max_length=128, verbose_name='RA Property'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registration Date'),
        ),
    ]
