# Generated by Django 2.0.3 on 2018-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0042_auto_20180904_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Internal Name'),
        ),
    ]
