# Generated by Django 2.0.3 on 2018-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0043_auto_20180904_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='database',
            field=models.CharField(blank=True, default='catalog', help_text='Database identifier in settings', max_length=128, null=True, verbose_name='Database'),
        ),
    ]
