# Generated by Django 2.0.3 on 2018-11-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0044_auto_20180904_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='asteroids',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of Asteroids'),
        ),
    ]
