# Generated by Django 2.0.3 on 2018-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0045_customlist_asteroids'),
    ]

    operations = [
        migrations.CreateModel(
            name='JohnstonArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=6, null=True, verbose_name='Number')),
                ('name', models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, null=True, verbose_name='Name')),
                ('provisional_designation', models.CharField(max_length=32, verbose_name='Provisional Designation')),
                ('dynamical_class', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Dynamical Class')),
                ('a', models.FloatField(blank=True, default=None, null=True, verbose_name='a (AU)')),
                ('e', models.FloatField(blank=True, default=None, null=True, verbose_name='e')),
                ('q', models.FloatField(blank=True, default=None, null=True, verbose_name='q (AU)')),
                ('Q', models.FloatField(blank=True, default=None, null=True, verbose_name='Q (AU)')),
                ('i', models.FloatField(blank=True, default=None, null=True, verbose_name='i (deg)')),
                ('diameter', models.FloatField(blank=True, default=None, null=True, verbose_name='Diameter (Km)')),
                ('diameter_flag', models.BooleanField(default=False, help_text='Diameter values marked by True are estimated assuming an albedo of 0.09 (or for secondary components, assuming the same albedo as the primary). Remaining diameter values have been determined by various methods (combined optical/thermal observations, dynamical fits/assumed densities for binaries, direct imagery, or stellar occultation).', verbose_name='Diameter Flag')),
                ('albedo', models.FloatField(blank=True, default=None, null=True, verbose_name='Albedo')),
                ('b_r_mag', models.FloatField(blank=True, default=None, help_text='B-R magnitude is the difference between blue filter magnitude and red filter magnitude; values greater than 1.03 indicate spectra redder than that of the Sun.', null=True, verbose_name='B-R mag')),
                ('taxon', models.CharField(blank=True, default=None, help_text='Taxonomic type is from Belskaya et al., 2015, Icarus, 250:482-491.', max_length=10, null=True, verbose_name='Taxon Type')),
                ('density', models.FloatField(blank=True, default=None, null=True, verbose_name='Density (g/cm^3)')),
                ('known_components', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="known add'l components")),
                ('discovery', models.DateField(blank=True, default=None, null=True, verbose_name='Night')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
            ],
        ),
    ]
