# Generated by Django 2.0.3 on 2018-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0046_johnstonarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='johnstonarchive',
            name='Q',
        ),
        migrations.RemoveField(
            model_name='johnstonarchive',
            name='q',
        ),
        migrations.AddField(
            model_name='johnstonarchive',
            name='aphelion_distance',
            field=models.FloatField(blank=True, default=None, help_text='Q (AU) aphelion distance', null=True, verbose_name='Q (AU)'),
        ),
        migrations.AddField(
            model_name='johnstonarchive',
            name='perihelion_distance',
            field=models.FloatField(blank=True, default=None, help_text='q (AU) perihelion distance', null=True, verbose_name='q (AU)'),
        ),
    ]
