# Generated by Django 2.0.3 on 2018-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0047_auto_20181204_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='johnstonarchive',
            name='aphelion_distance',
            field=models.FloatField(blank=True, default=None, help_text='Q (AU) aphelion distance', null=True, verbose_name='aphelion distance'),
        ),
        migrations.AlterField(
            model_name='johnstonarchive',
            name='discovery',
            field=models.DateField(blank=True, default=None, help_text='Discovery Year-Month', null=True, verbose_name='Discovery'),
        ),
        migrations.AlterField(
            model_name='johnstonarchive',
            name='perihelion_distance',
            field=models.FloatField(blank=True, default=None, help_text='q (AU) perihelion distance', null=True, verbose_name='perihelion distance'),
        ),
    ]
