# Generated by Django 2.0.3 on 2019-01-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0048_auto_20181204_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skybotoutput',
            unique_together={('num', 'name', 'expnum')},
        ),
    ]
