# Generated by Django 2.0.3 on 2019-02-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0050_skybotrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Final'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='date_initial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Initial'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_cent',
            field=models.FloatField(blank=True, null=True, verbose_name='Dec Cent'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_cent',
            field=models.FloatField(blank=True, null=True, verbose_name='Ra Cent'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='type_run',
            field=models.CharField(choices=[('all', 'All'), ('period', 'Period'), ('circle', 'Circle'), ('square', 'Square')], default='all', max_length=30, verbose_name='Type Run'),
        ),
    ]
