# Generated by Django 2.0.3 on 2019-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0050_skybotrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skybotrun',
            name='finish_skybot',
        ),
        migrations.RemoveField(
            model_name='skybotrun',
            name='start_skybot',
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
