# Generated by Django 2.0.3 on 2019-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0051_auto_20190212_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ll',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC LL'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_lr',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC LR'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ul',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC UL'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ur',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC UR'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ll',
            field=models.FloatField(blank=True, null=True, verbose_name='RA LL'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_lr',
            field=models.FloatField(blank=True, null=True, verbose_name='RA LR'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ul',
            field=models.FloatField(blank=True, null=True, verbose_name='RA UL'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ur',
            field=models.FloatField(blank=True, null=True, verbose_name='RA UR'),
        ),
    ]
