# Generated by Django 2.0.3 on 2019-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0051_auto_20190122_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='dateFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Initial'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dateInitial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Initial'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_cent',
            field=models.FloatField(blank=True, null=True, verbose_name='Dec Cent'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_cent',
            field=models.FloatField(blank=True, null=True, verbose_name='Ra Cent'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='typeRun',
            field=models.CharField(choices=[('all', 'All'), ('period', 'Period'), ('circle', 'Circle'), ('square', 'Square')], default='all', max_length=30, verbose_name='Type'),
        ),
    ]
