# Generated by Django 2.0.3 on 2019-02-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0052_auto_20190124_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skybotrun',
            name='typeRun',
        ),
    ]
