# Generated by Django 2.0.3 on 2019-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0052_auto_20190124_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skybotrun',
            old_name='dateFinal',
            new_name='date_initial',
        ),
        migrations.RenameField(
            model_name='skybotrun',
            old_name='typeRun',
            new_name='type_run',
        ),
        migrations.RemoveField(
            model_name='skybotrun',
            name='dateInitial',
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Final'),
        ),
    ]
