# Generated by Django 2.0.3 on 2019-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0052_auto_20190212_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotrun',
            name='ra_ll',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RA LL'),
        ),
        migrations.AlterField(
            model_name='skybotrun',
            name='ra_lr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RA LR'),
        ),
        migrations.AlterField(
            model_name='skybotrun',
            name='ra_ul',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RA UL'),
        ),
        migrations.AlterField(
            model_name='skybotrun',
            name='ra_ur',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RA UR'),
        ),
    ]
