# Generated by Django 2.0.3 on 2019-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0053_remove_skybotrun_typerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='typeRun',
            field=models.CharField(choices=[('all', 'All'), ('period', 'Period'), ('circle', 'Circle'), ('square', 'Square')], default='all', max_length=30, verbose_name='Type'),
        ),
    ]
