# Generated by Django 2.0.3 on 2019-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0053_auto_20190130_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='radius',
            field=models.FloatField(blank=True, null=True, verbose_name='Radius'),
        ),
    ]
