# Generated by Django 2.0.3 on 2019-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0054_skybotrun_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ll',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC Lower Left'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_lr',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC Lower Right'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ul',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC Upper Left'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='dec_ur',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC Upper Right'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ll',
            field=models.FloatField(blank=True, null=True, verbose_name='RA Lower Left'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_lr',
            field=models.FloatField(blank=True, null=True, verbose_name='RA Lower Right'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ul',
            field=models.FloatField(blank=True, null=True, verbose_name='RA Upper Left'),
        ),
        migrations.AddField(
            model_name='skybotrun',
            name='ra_ur',
            field=models.FloatField(blank=True, null=True, verbose_name='RA Upper Right'),
        ),
    ]
