# Generated by Django 2.2.13 on 2021-07-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orbit", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BspJplFile",
        ),
        migrations.DeleteModel(
            name="ObservationFile",
        ),
        migrations.DeleteModel(
            name="OrbitalParameterFile",
        ),
        migrations.AlterUniqueTogether(
            name="refinedasteroid",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="refinedasteroid",
            name="orbit_run",
        ),
        migrations.RemoveField(
            model_name="refinedorbit",
            name="asteroid",
        ),
        migrations.RemoveField(
            model_name="refinedorbitinput",
            name="asteroid",
        ),
        migrations.DeleteModel(
            name="OrbitRun",
        ),
        migrations.DeleteModel(
            name="RefinedAsteroid",
        ),
        migrations.DeleteModel(
            name="RefinedOrbit",
        ),
        migrations.DeleteModel(
            name="RefinedOrbitInput",
        ),
    ]
