# Generated by Django 2.0.3 on 2018-08-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orbit', '0025_auto_20180821_2007'),
        ('tno', '0039_proccess_input_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
                ('average_time', models.FloatField(blank=True, null=True, verbose_name='Average Time')),
                ('count_objects', models.PositiveIntegerField(blank=True, help_text='Number of objects received as input', null=True, verbose_name='Num Objects')),
                ('count_executed', models.PositiveIntegerField(blank=True, help_text='Number of objects that were executed by NIMA.', null=True, verbose_name='Num Executed Objects')),
                ('count_not_executed', models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed by NIMA.', null=True, verbose_name='Num Not Executed Objects')),
                ('count_success', models.PositiveIntegerField(blank=True, help_text='Number of objects successfully executed', null=True, verbose_name='Count Success')),
                ('count_failed', models.PositiveIntegerField(blank=True, help_text='Number of failed objects', null=True, verbose_name='Count Failed')),
                ('count_warning', models.PositiveIntegerField(blank=True, help_text='Number of objects with status warning', null=True, verbose_name='Count Warning')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to the prediction occultation directory, this is the internal path in the proccess directory.', max_length=256, null=True, verbose_name='Relative Path')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10, null=True, verbose_name='Status')),
                ('input_list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_input_list', to='tno.CustomList', verbose_name='Input List')),
                ('input_orbit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_input_orbit_run', to='orbit.OrbitRun', verbose_name='Orbit Run')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('proccess', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_run', to='tno.Proccess', verbose_name='Proccess')),
            ],
        ),
    ]
