# Generated by Django 2.0.3 on 2018-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictrun',
            name='count_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were executed by Praia Occultation.', null=True, verbose_name='Num Executed Objects'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed by Praia Occultation.', null=True, verbose_name='Num Not Executed Objects'),
        ),
    ]
