# Generated by Django 2.0.3 on 2018-08-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20180828_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefinedAsteroid',
            new_name='PredictAsteroid',
        ),
    ]
