# Generated by Django 2.0.3 on 2018-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20180828_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeapSeconds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Internal name', max_length=100, null=True, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, help_text='Display Name.', max_length=100, null=True, verbose_name='Display name')),
                ('url', models.URLField(blank=True, help_text='URL of archives.', max_length=100, null=True, verbose_name='URL')),
                ('upload', models.FileField(blank=True, help_text='Upload of archives.', null=True, upload_to='uploads/', verbose_name='Upload')),
            ],
        ),
    ]
