# Generated by Django 2.0.3 on 2018-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_leapseconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BspPlanetaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Internal name', max_length=100, null=True, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, help_text='Display Name.', max_length=100, null=True, verbose_name='Display name')),
                ('url', models.URLField(blank=True, help_text='URL of archives.', max_length=100, null=True, verbose_name='URL')),
                ('upload', models.FileField(blank=True, help_text='Upload of archives.', null=True, upload_to='leap_seconds', verbose_name='file')),
            ],
        ),
        migrations.AlterField(
            model_name='leapseconds',
            name='upload',
            field=models.FileField(blank=True, help_text='Upload of archives.', null=True, upload_to='leap_seconds', verbose_name='file'),
        ),
    ]
