# Generated by Django 2.0.3 on 2018-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20180911_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bspplanetaria',
            name='upload',
            field=models.FileField(blank=True, help_text='Upload of archives.', null=True, upload_to='bsp_planetaria', verbose_name='file'),
        ),
    ]
