# Generated by Django 2.0.3 on 2018-10-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_auto_20180911_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeapSeconds',
            new_name='LeapSecond',
        ),
    ]
