# Generated by Django 2.0.3 on 2018-10-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_auto_20181001_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='bsp_planetary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.BspPlanetary', verbose_name='BSP Planetary'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='leap_second',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.LeapSecond', verbose_name='Leap Second'),
        ),
    ]
