# Generated by Django 2.0.3 on 2018-10-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0044_auto_20180904_1816'),
        ('predict', '0010_auto_20181001_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='catalog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Catalog', verbose_name='Catalog'),
        ),
    ]
