# Generated by Django 2.0.3 on 2018-10-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_predictrun_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='catalog_radius',
            field=models.FloatField(default=0.15, help_text='Radius in degrees for the querys in the star catalog.', verbose_name='Catalog Radius'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='ephemeris_end_date',
            field=models.DateTimeField(blank=True, help_text='Final date to generate Ephemeris', null=True, verbose_name='Ephemers End Date'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='ephemeris_start_date',
            field=models.DateField(blank=True, help_text='Initial date to generate Ephemeris', null=True, verbose_name='Ephemeris Start Date'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='ephemeris_step',
            field=models.PositiveIntegerField(default=600, help_text='Interval in seconds to generate Ephemeris', verbose_name='Ephemeris Step'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='bsp_planetary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.BspPlanetary', verbose_name='BSP Planetary'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Catalog', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='leap_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.LeapSecond', verbose_name='Leap Second'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='proccess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_run', to='tno.Proccess', verbose_name='Proccess'),
        ),
    ]
