# Generated by Django 2.0.3 on 2018-10-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0044_auto_20180904_1816'),
        ('predict', '0012_auto_20181015_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictrun',
            name='proccess',
        ),
        migrations.AddField(
            model_name='predictrun',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_run', to='tno.Proccess', verbose_name='Process'),
        ),
    ]
