# Generated by Django 2.0.3 on 2018-10-23 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_auto_20181023_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictrun',
            name='bsp_planetary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='predict.BspPlanetary', verbose_name='BSP Planetary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tno.Catalog', verbose_name='Catalog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='ephemeris_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Final date to generate Ephemeris', verbose_name='Ephemers End Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='ephemeris_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Initial date to generate Ephemeris', verbose_name='Ephemeris Start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='leap_second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='predict.LeapSecond', verbose_name='Leap Second'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predict_run', to='tno.Proccess', verbose_name='Process'),
            preserve_default=False,
        ),
    ]
