# Generated by Django 2.0.3 on 2018-10-23 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0014_auto_20181023_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictrun',
            name='input_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='predict_input_list', to='tno.CustomList', verbose_name='Input List'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='input_orbit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='predict_input_orbit_run', to='orbit.OrbitRun', verbose_name='Orbit Run'),
        ),
    ]
