# Generated by Django 2.0.3 on 2018-10-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0015_auto_20181023_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictrun',
            old_name='ephemeris_end_date',
            new_name='ephemeris_final_date',
        ),
        migrations.RenameField(
            model_name='predictrun',
            old_name='ephemeris_start_date',
            new_name='ephemeris_initial_date',
        ),
    ]
