# Generated by Django 2.0.3 on 2018-10-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0016_auto_20181023_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictrun',
            name='ephemeris_initial_date',
            field=models.DateTimeField(help_text='Initial date to generate Ephemeris', verbose_name='Ephemeris Start Date'),
        ),
    ]
