# Generated by Django 2.0.3 on 2018-10-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0017_auto_20181023_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='execution_catalog',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Catalog'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_dates',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Dates'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_ephemeris',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Ephemeris'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_maps',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Maps'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_register',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Register'),
        ),
        migrations.AlterField(
            model_name='predictrun',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
