# Generated by Django 2.0.3 on 2018-10-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0018_auto_20181025_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictrun',
            name='execution_catalog',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='execution_dates',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='execution_ephemeris',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='execution_maps',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='execution_register',
        ),
    ]
