# Generated by Django 2.0.3 on 2018-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0019_auto_20181026_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='execution_catalog',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Catalog'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_dates',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Dates'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_ephemeris',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Ephemeris'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_maps',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Maps'),
        ),
        migrations.AddField(
            model_name='predictrun',
            name='execution_register',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Register'),
        ),
    ]
