# Generated by Django 2.0.3 on 2018-10-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0020_auto_20181026_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictrun',
            name='count_executed',
        ),
        migrations.RemoveField(
            model_name='predictrun',
            name='count_not_executed',
        ),
    ]
