# Generated by Django 2.0.3 on 2018-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0021_auto_20181026_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictasteroid',
            name='execution_ephemeris',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Ephemeris'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='finish_ephemeris',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Ephemeris'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='start_ephemeris',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Ephemeris'),
        ),
    ]
