# Generated by Django 2.0.3 on 2018-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0022_auto_20181026_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictasteroid',
            name='catalog_rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Catalog Rows'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='execution_catalog',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Catalog'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='execution_maps',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Maps'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='execution_search_candidate',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Search Candidate'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='finish_catalog',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Catalog'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='finish_maps',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Maps'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='finish_search_candidate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Search Candidate'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='start_catalog',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Catalog'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='start_maps',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Maps'),
        ),
        migrations.AddField(
            model_name='predictasteroid',
            name='start_search_candidate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Search Candidate'),
        ),
    ]
