# Generated by Django 2.0.3 on 2018-10-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0023_auto_20181026_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictasteroid',
            name='absolute_path',
        ),
        migrations.RemoveField(
            model_name='predictasteroid',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='predictasteroid',
            name='start_time',
        ),
    ]
