# Generated by Django 2.0.3 on 2018-10-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0024_auto_20181026_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('dates_file', 'Dates'), ('bsp_planetary', 'Planetary Ephemeris'), ('bsp_asteroid', 'Asteroid JPL Ephemeris'), ('leap_second', 'Leap Second'), ('positions', 'Positions'), ('ephemeris', 'Ephemeris'), ('catalog', 'Catalog')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date Time')),
                ('filename', models.CharField(max_length=256, verbose_name='Filename')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='Relative Path')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='predict.PredictAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
