# Generated by Django 2.0.3 on 2018-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0025_predictinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictinput',
            name='date_time',
        ),
    ]
