# Generated by Django 2.0.3 on 2018-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0026_remove_predictinput_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictinput',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File Size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='predictinput',
            name='file_type',
            field=models.CharField(blank=True, help_text="File extension like '.txt'", max_length=10, null=True, verbose_name='File Type'),
        ),
    ]
