# Generated by Django 2.0.3 on 2018-10-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0027_auto_20181029_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ephemeris', 'Ephemeris'), ('radec', 'RA Dec'), ('positions', 'Positions'), ('catalog', 'Catalog'), ('star_catalog_mini', 'Star Catalog Mini'), ('star_catalog_xy', 'Start Catalog XY'), ('stars_parameters_of_occultation', 'Start Parameters of Occultation'), ('stars_parameters_of_occultation_table', 'Start Parameters of Occultation Table')], help_text='Description of the result type.', max_length=60, verbose_name='Input Type')),
                ('filename', models.CharField(help_text='Filename is formed by name without space and separated by underline.', max_length=256, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(help_text='File Size in bytes', verbose_name='File Size')),
                ('file_type', models.CharField(help_text="File extension like '.txt'", max_length=10, verbose_name='File Type')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='Relative Path')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_result', to='predict.PredictAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
