# Generated by Django 2.0.3 on 2018-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0028_predictoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictoutput',
            name='relative_path',
        ),
        migrations.AddField(
            model_name='predictoutput',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='File Path'),
        ),
    ]
