# Generated by Django 2.0.3 on 2018-10-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0031_auto_20181030_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='occultation',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to file, this is the internal path in the proccess directory.', max_length=2000, null=True, verbose_name='File Path'),
        ),
    ]
