# Generated by Django 2.0.3 on 2018-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0033_auto_20181114_1204'),
        ('predict', '0033_auto_20181120_2253'),
    ]

    operations = [
    ]
