# Generated by Django 2.0.3 on 2018-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0034_merge_20181121_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictasteroid',
            name='diameter',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Diameter (Km)'),
        ),
    ]
