# Generated by Django 2.0.3 on 2018-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0035_predictasteroid_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictrun',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
