# Generated by Django 2.0.3 on 2018-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0035_predictasteroid_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='execution_search_candidate',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Search Candidate'),
        ),
        migrations.AlterField(
            model_name='predictasteroid',
            name='catalog_rows',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Catalog Rows'),
        ),
        migrations.AlterField(
            model_name='predictinput',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File Size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='predictoutput',
            name='file_size',
            field=models.BigIntegerField(help_text='File Size in bytes', verbose_name='File Size'),
        ),
    ]
