# Generated by Django 2.0.3 on 2018-12-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0036_auto_20181211_1737'),
        ('predict', '0036_auto_20181214_1243'),
    ]

    operations = [
    ]
