# Generated by Django 2.0.3 on 2018-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0037_merge_20181217_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrun',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed.', null=True, verbose_name='Num Not Executed Objects'),
        ),
        migrations.AlterField(
            model_name='predictasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
