# Generated by Django 2.0.3 on 2018-12-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0038_auto_20181217_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
    ]
