# Generated by Django 2.0.3 on 2019-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0039_auto_20181219_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictoutput',
            name='type',
            field=models.CharField(choices=[('ephemeris', 'Ephemeris'), ('radec', 'RA Dec'), ('positions', 'Positions'), ('asteroid_orbit', 'Asteroid Orbit'), ('catalog', 'Catalog'), ('catalog_csv', 'Catalog CSV'), ('stars_catalog_mini', 'Star Catalog Mini'), ('stars_catalog_xy', 'Start Catalog XY'), ('stars_parameters_of_occultation', 'Start Parameters of Occultation'), ('stars_parameters_of_occultation_plot', 'Start Parameters of Occultation Table'), ('occultation_table', 'Occultation Table CSV')], help_text='Description of the result type.', max_length=60, verbose_name='Type'),
        ),
    ]
