# Generated by Django 3.2.18 on 2024-03-26 18:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "activation_code",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Codigo utilizado para identificar o usuario ao inves de usar email.",
                        max_length=32,
                        verbose_name="Activation Code",
                    ),
                ),
                (
                    "subscribe_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscribe Date"
                    ),
                ),
                (
                    "unsubscribe_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Unsubscribe Date",
                    ),
                ),
                (
                    "unsubscribe",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que o usuario desativou a sua inscricao.",
                        verbose_name="Unsubscribe",
                    ),
                ),
            ],
        ),
    ]
