# Generated by Django 3.2.18 on 2024-03-26 18:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="activation_code",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Codigo utilizado para identificar o usuario ao inves de usar email.",
                max_length=40,
                verbose_name="Activation Code",
            ),
        ),
    ]
