# Generated by Django 3.2.18 on 2024-05-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_auto_20240507_1238"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfilter",
            name="preference_id",
        ),
        migrations.AddField(
            model_name="eventfilter",
            name="subscription_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.subscription",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
    ]
