# Generated by Django 3.2.18 on 2024-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_auto_20240510_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfilter",
            name="alt",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Altitude em kilometros.",
                null=True,
                verbose_name="Altitude",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="diameter",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Diametro do objeto.",
                null=True,
                verbose_name="Diameter",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="event_duration",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Duraçao da ocorrencia do evento.",
                null=True,
                verbose_name="Event Duration",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="filter_type",
            field=models.CharField(
                blank=True,
                help_text="Filtro que permite escolher entre objeto, classe ou subclasse.",
                max_length=50,
                null=True,
                verbose_name="Filter Type",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="geo_location",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Filtro de geolocalizaçao.",
                null=True,
                verbose_name="Geo Location",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="lat",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Latitude em graus.",
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="local_solar_time_after",
            field=models.TimeField(
                blank=True,
                default=None,
                help_text="Restringir o instante mais próximo de uma hora local específica (em termos de longitude).",
                null=True,
                verbose_name="Local Solar Time",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="local_solar_time_before",
            field=models.TimeField(
                blank=True,
                default=None,
                help_text="Restringir o instante mais próximo de uma hora local específica (em termos de longitude).",
                null=True,
                verbose_name="Local Solar Time",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="lon",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Longitude em graus.",
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="magnitude",
            field=models.IntegerField(
                blank=True,
                default=15,
                help_text="Magnitude do objeto.",
                null=True,
                verbose_name="Magnitude",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="magnitude_drop",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Magnitude Drop.",
                null=True,
                verbose_name="Magnitude Drop",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="radius",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Raio em kilometro.",
                null=True,
                verbose_name="Radius",
            ),
        ),
    ]
