# Generated by Django 3.2.18 on 2024-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_alter_eventfilter_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfilter",
            name="filter_value",
            field=models.TextField(
                blank=True,
                help_text="Valor que será utilizado no filtro.",
                null=True,
                verbose_name="Filter Value",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="geo_location",
            field=models.BooleanField(
                default=False,
                help_text="Filtro de geolocalizaçao.",
                verbose_name="Geo Location",
            ),
        ),
    ]
