# Generated by Django 3.2.18 on 2024-05-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20240510_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfilter',
            old_name='alt',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='eventfilter',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='eventfilter',
            old_name='radius',
            new_name='location_radius',
        ),
        migrations.RenameField(
            model_name='eventfilter',
            old_name='lon',
            new_name='longitude',
        ),
    ]
