# Generated by Django 3.2.18 on 2024-06-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20240510_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfilter',
            name='filter_type',
            field=models.CharField(choices=[('name', 'Object name'), ('dynclass', 'Dynamic class (with subclasses)'), ('base_dynclass', 'Dynamic class')], default='name', help_text='Filtro que permite escolher entre objeto, classe ou subclasse.', max_length=15, verbose_name='Filter Type'),
        ),
    ]
