# Generated by Django 3.2.18 on 2024-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_eventfilter_filter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfilter',
            old_name='diameter',
            new_name='diameter_max',
        ),
        migrations.AddField(
            model_name='eventfilter',
            name='diameter_min',
            field=models.IntegerField(blank=True, default=None, help_text='Diametro do objeto.', null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='eventfilter',
            name='location_radius',
            field=models.IntegerField(blank=True, default=None, help_text='Raio em kilometro.', null=True, verbose_name='Radius'),
        ),
    ]
