# Generated by Django 3.2.18 on 2024-07-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0012_auto_20240628_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfilter",
            name="geo_location",
        ),
    ]
