# Generated by Django 3.2.18 on 2024-08-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0013_remove_eventfilter_geo_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="email",
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
