# Generated by Django 3.2.18 on 2024-08-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0016_auto_20240815_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfilter",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_filter",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
