# Generated by Django 3.2.18 on 2024-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0017_alter_eventfilter_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfilter",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Description"
            ),
        ),
    ]
