# Generated by Django 3.2.18 on 2024-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_alter_eventfilter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfilter',
            name='closest_approach_uncertainty_in_km',
            field=models.IntegerField(blank=True, default=None, help_text='Uncertainty in geocentric closest approach (km).', null=True, verbose_name='Uncertainty (km)'),
        ),
    ]
