# Generated by Django 3.2.18 on 2024-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0022_eventfilter_closest_approach_uncertainty_in_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="events_count",
            field=models.IntegerField(
                default=0,
                help_text="Contagem dos eventos.",
                verbose_name="Events Count",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="prepared",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a submmissao foi preparada ou nao.",
                verbose_name="Prepared",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="sending",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a submissao está sendo enviada ou nao.",
                verbose_name="Sending",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="sent",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a submissao foi enviada ou nao.",
                verbose_name="Sent",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="title",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Titulo da submissao.",
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
