# Generated by Django 3.2.18 on 2024-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0024_remove_submission_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Indica se a data de envio da submissao.', null=True, verbose_name='Sent Date'),
        ),
    ]
