# Generated by Django 3.2.18 on 2024-11-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0025_submission_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='subscription_id',
        ),
    ]
