# Generated by Django 3.2.18 on 2024-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0026_remove_submission_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfilter",
            name="filter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("name", "Object name"),
                    ("dynclass", "Dynamic class (with subclasses)"),
                    ("base_dynclass", "Dynamic class"),
                ],
                default="name",
                help_text="Filtro que permite escolher entre objeto, classe ou subclasse.",
                max_length=15,
                verbose_name="Filter Type",
            ),
        ),
    ]
