# Generated by Django 3.2.18 on 2024-11-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0027_alter_eventfilter_filter_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventfilter",
            old_name="closest_approach_uncertainty_in_km",
            new_name="closest_approach_uncertainty_km",
        ),
    ]
