# Generated by Django 3.2.18 on 2024-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0029_auto_20241113_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfilter",
            name="frequency",
            field=models.IntegerField(
                choices=[(1, "Monthly"), (2, "Weekly"), (3, "Daily")],
                default=1,
                help_text="Frequencia de recebimento do periodico 1-mensal, 2-semanal, 3-diario.",
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilter",
            name="location_radius",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Raio em kilometro.",
                null=True,
                verbose_name="Radius",
            ),
        ),
    ]
