# Generated by Django 3.2.18 on 2024-11-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0030_auto_20241118_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='sending',
        ),
    ]
