# Generated by Django 3.2.18 on 2024-11-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0032_submission_sending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='sending_date',
        ),
    ]
