# Generated by Django 3.2.18 on 2024-11-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0033_remove_submission_sending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.AddField(
            model_name='eventfilter',
            name='attachment',
            field=models.ForeignKey(blank=True, help_text='Attachment associated with this event filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_filters', to='newsletter.attachment', verbose_name='Attachment'),
        ),
    ]
