# Generated by Django 3.2.18 on 2024-11-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0034_auto_20241122_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfilter",
            name="attachment",
        ),
        migrations.AddField(
            model_name="submission",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Attachment associated with this submission.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_attachments",
                to="newsletter.attachment",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="submission_id",
            field=models.ForeignKey(
                help_text="Submission associated with this attachment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_submissions",
                to="newsletter.submission",
                verbose_name="Submission",
            ),
        ),
    ]
