# Generated by Django 2.0.12 on 2020-06-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybot', '0002_auto_20200611_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start'),
        ),
    ]
