# Generated by Django 2.0.3 on 2019-07-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometryAsteroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, verbose_name='Name')),
                ('number', models.CharField(blank=True, default=None, help_text='(ucd=“meta.id;meta.number”) Object number (not all objects have numbers assigned).', max_length=6, null=True, verbose_name='Number')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=15, null=True, verbose_name='Status')),
                ('error_msg', models.CharField(blank=True, help_text='When the status is failure, this field should contain a message with the error.', max_length=256, null=True, verbose_name='Error Message')),
                ('relative_path', models.CharField(blank=True, help_text='Path relative to the Astrometry OBJECT directory, this is the internal path in the proccess directory.', max_length=256, null=True, verbose_name='Relative Path')),
            ],
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('reexecute', 'Reexecute')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='astrometry_run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asteroids', to='praia.Run', verbose_name='Astrometry Run'),
        ),
        migrations.AlterUniqueTogether(
            name='astrometryasteroid',
            unique_together={('astrometry_run', 'name')},
        ),
    ]
