# Generated by Django 2.0.3 on 2018-06-12 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('praia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PraiaConfig',
            new_name='Configuration',
        ),
        migrations.RenameModel(
            old_name='PraiaRuns',
            new_name='Run',
        ),
    ]
