# Generated by Django 2.0.3 on 2019-07-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0002_auto_20190704_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometryInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('dates_file', 'Dates'), ('bsp_planetary', 'Planetary Ephemeris'), ('bsp_asteroid', 'Asteroid JPL Ephemeris'), ('leap_second', 'Leap Second'), ('positions', 'Positions'), ('ephemeris', 'Ephemeris'), ('catalog', 'Catalog')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type')),
                ('filename', models.CharField(max_length=256, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File Size in bytes', null=True, verbose_name='File Size')),
                ('file_type', models.CharField(blank=True, help_text="File extension like '.txt'", max_length=10, null=True, verbose_name='File Type')),
                ('file_path', models.CharField(blank=True, help_text='Path to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='File Path')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='praia.AstrometryAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
