# Generated by Django 2.0.3 on 2018-06-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0028_proccess_praia'),
        ('praia', '0002_auto_20180612_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='config',
        ),
        migrations.AddField(
            model_name='run',
            name='configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='praia.Configuration', verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='run',
            name='input_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.CustomList', verbose_name='Input List'),
        ),
    ]
