# Generated by Django 2.0.3 on 2019-07-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0003_astrometryinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometryOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ephemeris', 'Ephemeris'), ('radec', 'RA Dec'), ('positions', 'Positions'), ('asteroid_orbit', 'Asteroid Orbit'), ('neighborhood_stars', 'Neighborhood Stars'), ('catalog', 'Catalog'), ('catalog_csv', 'Catalog CSV'), ('stars_catalog_mini', 'Star Catalog Mini'), ('stars_catalog_xy', 'Start Catalog XY'), ('stars_parameters_of_occultation', 'Start Parameters of Occultation'), ('stars_parameters_of_occultation_plot', 'Start Parameters of Occultation Table'), ('occultation_table', 'Occultation Table CSV')], help_text='Description of the result type.', max_length=60, verbose_name='Type')),
                ('filename', models.CharField(help_text='Filename is formed by name without space and separated by underline.', max_length=256, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(help_text='File Size in bytes', verbose_name='File Size')),
                ('file_type', models.CharField(help_text="File extension like '.txt'", max_length=10, verbose_name='File Type')),
                ('file_path', models.CharField(blank=True, help_text='Path to file, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='File Path')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrometry_result', to='praia.AstrometryAsteroid', verbose_name='Asteroid')),
            ],
        ),
    ]
