# Generated by Django 2.0.3 on 2019-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0003_astrometryinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='count_objects',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects received as input', null=True, verbose_name='Num Objects'),
        ),
        migrations.AddField(
            model_name='run',
            name='error_msg',
            field=models.CharField(blank=True, help_text='When the status is failure, this field should contain a message with the error.', max_length=256, null=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='run',
            name='error_traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Error Traceback'),
        ),
        migrations.AddField(
            model_name='run',
            name='execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='input_type',
            field=models.CharField(choices=[('ccd_images_list', 'CCD Images List')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type'),
        ),
    ]
