# Generated by Django 2.0.3 on 2019-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0004_auto_20190705_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryinput',
            name='error_msg',
            field=models.CharField(blank=True, help_text='This field contains the error message that occurred during the creation of the Input.', max_length=256, null=True, verbose_name='Error Message'),
        ),
    ]
