# Generated by Django 2.0.3 on 2018-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0004_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Time'),
        ),
    ]
