# Generated by Django 2.0.3 on 2018-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0005_auto_20180626_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Path relative to the astrometry directory, this is the internal path in the container.', max_length=256, null=True, verbose_name='Relative Path'),
        ),
    ]
