# Generated by Django 2.0.3 on 2018-07-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0035_auto_20180703_2013'),
        ('praia', '0006_run_relative_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='proccess',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Proccess', verbose_name='Proccess'),
        ),
    ]
