# Generated by Django 2.0.3 on 2019-07-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0006_auto_20190705_1633'),
        ('praia', '0004_astrometryoutput'),
    ]

    operations = [
    ]
