# Generated by Django 2.0.3 on 2019-07-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0007_merge_20190705_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='astrometryinput',
            unique_together={('asteroid', 'input_type')},
        ),
    ]
