# Generated by Django 2.0.3 on 2018-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0007_run_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Path relative to the astrometry directory, this is the internal path in the proccess directory.', max_length=256, null=True, verbose_name='Relative Path'),
        ),
    ]
