# Generated by Django 2.0.3 on 2019-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0008_auto_20190705_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='ccd_images',
            field=models.BigIntegerField(blank=True, help_text='Number of CCDs for this asteroid.', null=True, verbose_name='CCD Images'),
        ),
    ]
