# Generated by Django 2.0.3 on 2019-07-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0005_auto_20190416_1854'),
        ('praia', '0009_astrometryasteroid_ccd_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='catalog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tno.Catalog', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='input_type',
            field=models.CharField(choices=[('ccd_images_list', 'CCD Images List'), ('bsp_jpl', 'BSP JPL')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type'),
        ),
    ]
