# Generated by Django 2.0.3 on 2019-07-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0010_auto_20190709_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='catalog_rows',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Catalog Rows'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='input_type',
            field=models.CharField(choices=[('ccd_images_list', 'CCD Images List'), ('bsp_jpl', 'BSP JPL'), ('catalog', 'Catalog')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type'),
        ),
    ]
