# Generated by Django 2.0.3 on 2019-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0011_auto_20190710_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
    ]
