# Generated by Django 2.0.3 on 2019-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0012_astrometryasteroid_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='error_msg',
            field=models.CharField(blank=True, help_text='When the status is failure, this field should contain a message with the error.', max_length=2048, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Path relative to the Astrometry OBJECT directory, this is the internal path in the proccess directory.', max_length=1024, null=True, verbose_name='Relative Path'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='error_msg',
            field=models.CharField(blank=True, help_text='This field contains the error message that occurred during the creation of the Input.', max_length=2048, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='filename',
            field=models.CharField(max_length=1024, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='filename',
            field=models.CharField(help_text='Filename is formed by name without space and separated by underline.', max_length=1024, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='run',
            name='error_msg',
            field=models.CharField(blank=True, help_text='When the status is failure, this field should contain a message with the error.', max_length=2048, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='run',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Path relative to the astrometry directory, this is the internal path in the proccess directory.', max_length=2048, null=True, verbose_name='Relative Path'),
        ),
    ]
