# Generated by Django 2.0.3 on 2019-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0013_auto_20190715_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='count_failed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of failed objects', null=True, verbose_name='Count Failed'),
        ),
        migrations.AddField(
            model_name='run',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed.', null=True, verbose_name='Num Not Executed Objects'),
        ),
        migrations.AddField(
            model_name='run',
            name='count_success',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects successfully executed', null=True, verbose_name='Count Success'),
        ),
        migrations.AddField(
            model_name='run',
            name='count_warning',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects with status warning', null=True, verbose_name='Count Warning'),
        ),
    ]
