# Generated by Django 2.0.3 on 2019-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0014_auto_20190715_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('warning', 'Warning'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
    ]
