# Generated by Django 2.0.3 on 2019-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0014_auto_20190715_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='steps',
            field=models.CharField(blank=True, choices=[('0', 'CCD Images'), ('1', 'Bsp Jpl'), ('2', 'Gaia Catalog'), ('3', 'Praia Astrometry'), ('4', 'Registered')], default='0', max_length=10, null=True, verbose_name='Steps'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('warning', 'Warning'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
    ]
