# Generated by Django 2.0.3 on 2019-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0015_auto_20190717_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='steps',
            field=models.IntegerField(blank=True, choices=[(0, 'CCD Images'), (1, 'Bsp Jpl'), (2, 'Gaia Catalog'), (3, 'Praia Astrometry'), (4, 'Registered')], default='0', max_length=10, null=True, verbose_name='Steps'),
        ),
    ]
