# Generated by Django 2.0.3 on 2019-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0017_auto_20190717_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='steps',
        ),
        migrations.AddField(
            model_name='run',
            name='step',
            field=models.IntegerField(blank=True, choices=[(0, 'CCD Images'), (1, 'Bsp Jpl'), (2, 'Gaia Catalog'), (3, 'Praia Astrometry'), (4, 'Registered')], default=0, null=True, verbose_name='Current Step'),
        ),
    ]
