# Generated by Django 2.0.3 on 2019-07-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0018_auto_20190718_1344'),
        ('praia', '0015_auto_20190718_1408'),
    ]

    operations = [
    ]
