# Generated by Django 2.0.3 on 2019-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0019_merge_20190722_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='execution_bsp_jpl',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution BSP JPL'),
        ),
        migrations.AddField(
            model_name='run',
            name='execution_catalog',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Catalog'),
        ),
        migrations.AddField(
            model_name='run',
            name='execution_ccd_images',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution CCD Images'),
        ),
        migrations.AlterField(
            model_name='run',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed.', null=True, verbose_name='Count Not Executed'),
        ),
        migrations.AlterField(
            model_name='run',
            name='count_objects',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects received as input', null=True, verbose_name='Count Asteroids'),
        ),
    ]
