# Generated by Django 2.0.3 on 2019-07-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0019_merge_20190722_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometryJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterid', models.BigIntegerField(blank=True, null=True, verbose_name='Cluster Id')),
                ('procid', models.IntegerField(blank=True, null=True, verbose_name='Proc Id')),
                ('job_status', models.IntegerField(blank=True, choices=[(0, 'Unexpanded'), (1, 'Idle'), (2, 'Running'), (3, 'Removed'), (4, 'Completed'), (5, 'Held'), (6, 'Submission')], null=True, verbose_name='Job Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
            ],
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('warning', 'Warning'), ('success', 'Success'), ('failure', 'Failure'), ('not_executed', 'Not Executed'), ('idle', 'Idle')], default='pending', max_length=15, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='run',
            name='count_not_executed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects that were NOT executed.', null=True, verbose_name='Count Not Executed'),
        ),
        migrations.AlterField(
            model_name='run',
            name='count_objects',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects received as input', null=True, verbose_name='Count Asteroids'),
        ),
        migrations.AddField(
            model_name='astrometryjobs',
            name='asteroid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condor_job', to='praia.AstrometryAsteroid', verbose_name='Asteroid'),
        ),
        migrations.AddField(
            model_name='astrometryjobs',
            name='astrometry_run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='condor_jobs', to='praia.Run', verbose_name='Astrometry Run'),
        ),
    ]
