# Generated by Django 2.0.3 on 2019-07-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0020_auto_20190722_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AstrometryJobs',
            new_name='AstrometryJob',
        ),
    ]
