# Generated by Django 2.0.3 on 2019-07-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0020_auto_20190722_1655'),
        ('praia', '0021_auto_20190722_2027'),
    ]

    operations = [
    ]
