# Generated by Django 2.0.3 on 2019-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0022_merge_20190729_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryjob',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Cluster Name'),
        ),
        migrations.AddField(
            model_name='astrometryjob',
            name='global_job_id',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Global Job Id'),
        ),
        migrations.AddField(
            model_name='astrometryjob',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submit Time'),
        ),
    ]
