# Generated by Django 2.0.3 on 2019-08-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0023_auto_20190802_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryjob',
            name='args',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Args'),
        ),
        migrations.AddField(
            model_name='astrometryjob',
            name='remote_host',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Remote Host'),
        ),
    ]
