# Generated by Django 2.0.3 on 2019-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0024_auto_20190802_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryoutput',
            name='catalog',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Reference Catalog'),
        ),
        migrations.AddField(
            model_name='astrometryoutput',
            name='ccd_image',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='CCD Image'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='filename',
            field=models.CharField(max_length=1024, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='type',
            field=models.CharField(choices=[('astrometry', 'Astrometry'), ('target_offset', 'Target Offset'), ('targets', 'Targets')], help_text='Description of the result type.', max_length=60, verbose_name='Type'),
        ),
    ]
