# Generated by Django 2.0.3 on 2019-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0025_auto_20190808_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='processed_ccd_image',
            field=models.IntegerField(blank=True, default=0, help_text='Number of CCDs that were processed for this asteroid', null=True, verbose_name='Processed CCD Images'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='ccd_images',
            field=models.IntegerField(blank=True, default=0, help_text='Number of CCDs for this asteroid.', null=True, verbose_name='CCD Images'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='type',
            field=models.CharField(choices=[('astrometry', 'Astrometry'), ('target_offset', 'Target Offset'), ('targets', 'Targets'), ('astrometric_results', 'Astrometric Results (xy)'), ('saoimage_region_file', 'SAOimage region file'), ('mes', 'mes')], help_text='Description of the result type.', max_length=60, verbose_name='Type'),
        ),
    ]
