# Generated by Django 2.0.3 on 2019-08-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0026_auto_20190809_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometryjob',
            name='asteroid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condor_job', to='praia.AstrometryAsteroid', verbose_name='Asteroid'),
        ),
    ]
