# Generated by Django 2.0.3 on 2019-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0027_auto_20190809_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='execution_astrometry',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Astrometry'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reexecute', 'Reexecute'), ('failure', 'Failure')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='run',
            name='step',
            field=models.IntegerField(blank=True, choices=[(0, 'CCD Images'), (1, 'Bsp JPL'), (2, 'Reference Catalog'), (3, 'Praia Astrometry'), (4, 'Register')], default=0, null=True, verbose_name='Current Step'),
        ),
    ]
