# Generated by Django 2.0.3 on 2019-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0028_auto_20190809_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='condor_relative_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Condor Relative Path'),
        ),
        migrations.AlterField(
            model_name='run',
            name='step',
            field=models.IntegerField(blank=True, choices=[(0, 'CCD Images'), (1, 'Bsp JPL'), (2, 'Reference Catalog'), (3, 'Praia Astrometry'), (4, 'Done')], default=0, null=True, verbose_name='Current Step'),
        ),
    ]
