# Generated by Django 2.0.3 on 2019-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0029_auto_20190819_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='available_ccd_image',
            field=models.IntegerField(blank=True, default=0, help_text='Number of CCDs that were available for this asteroid', null=True, verbose_name='Available CCD Images'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_astrometry',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution PRAIA Astrometry'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_header',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Header Extraction'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_plots',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Plots'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_targets',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution PRAIA Targets'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='type',
            field=models.CharField(choices=[('astrometry', 'Astrometry'), ('target_offset', 'Target Offset'), ('targets', 'Targets'), ('astrometric_results', 'Astrometric Results (xy)'), ('saoimage_region_file', 'SAO image region file'), ('mes', 'mes'), ('header_extraction', 'Header Extraction'), ('ast_reduction', 'Astrometry Reduction'), ('ast_photometry', 'Astrometry Photometry'), ('astrometry_input', 'Astrometry Input'), ('astrometry_params', 'Astrometry Parameters'), ('astrometry_log', 'PRAIA Astrometry Log'), ('astrometry_plot', 'Plot')], help_text='Description of the result type.', max_length=60, verbose_name='Type'),
        ),
    ]
