# Generated by Django 2.0.3 on 2019-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0030_auto_20190909_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_registry',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Registry'),
        ),
    ]
