# Generated by Django 2.0.3 on 2019-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0031_astrometryasteroid_execution_registry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='astrometryoutput',
            index=models.Index(fields=['type'], name='praia_astro_type_cfa3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='astrometryoutput',
            index=models.Index(fields=['ccd_image'], name='praia_astro_ccd_ima_7a04a4_idx'),
        ),
        migrations.AddIndex(
            model_name='astrometryoutput',
            index=models.Index(fields=['file_type'], name='praia_astro_file_ty_b06b01_idx'),
        ),
    ]
