# Generated by Django 2.0.3 on 2019-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0032_auto_20190909_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='outputs',
            field=models.IntegerField(blank=True, default=0, help_text='Total outputs generated for this asteroid.', null=True, verbose_name='Outputs'),
        ),
    ]
