# Generated by Django 2.0.3 on 2019-09-18 14:23

from django.db import migrations, models
import django.db.models.deletion
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0033_astrometryasteroid_outputs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astrometryoutput',
            options={'ordering': ['ccd_image', 'type', 'catalog']},
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_time',
            field=models.DurationField(blank=True, default=timedelta, null=True, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='astrometryinput',
            name='input_type',
            field=models.CharField(choices=[('ccd_images_list', 'CCD Images List'), ('bsp_jpl', 'Ephemeris JPL'), ('catalog', 'Reference Catalog')], help_text='Description of the input type.', max_length=60, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='asteroid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ast_outputs', to='praia.AstrometryAsteroid', verbose_name='Asteroid'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='ccd_image',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='ID for Pointing'),
        ),
        migrations.AlterField(
            model_name='astrometryoutput',
            name='type',
            field=models.CharField(choices=[('astrometry', 'Astrometry'), ('target_offset', 'Target Offset'), ('targets', 'Targets'), ('targets_log', 'Target Search Log'), ('astrometric_results', 'Astrometric Results (xy)'), ('saoimage_region_file', 'SAO image region file'), ('mes', 'mes'), ('header_extraction', 'Header Extraction'), ('header_extraction_log', 'Header Extraction Log'), ('ast_reduction', 'Astrometry Reduction'), ('ast_photometry', 'Astrometry Photometry'), ('astrometry_input', 'Astrometry Input'), ('astrometry_params', 'Astrometry Parameters'), ('astrometry_log', 'PRAIA Astrometry Log'), ('astrometry_plot', 'Plot')], help_text='Description of the result type.', max_length=60, verbose_name='Type'),
        ),
    ]
