# Generated by Django 2.0.3 on 2019-09-18 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0034_auto_20190918_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_bsp_jpl',
            field=models.DurationField(blank=True, default=datetime.timedelta, help_text='Time taken to retrieve Ephemeris from JPL.', null=True, verbose_name='Execution Ephemeris JPL'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_ccd_list',
            field=models.DurationField(blank=True, default=datetime.timedelta, help_text='Time taken to retrieve list of asteroid-related ccds.', null=True, verbose_name='Execution CCD List'),
        ),
        migrations.AddField(
            model_name='astrometryasteroid',
            name='execution_reference_catalog',
            field=models.DurationField(blank=True, default=datetime.timedelta, help_text='Time taken to query stars in Reference Catalog.', null=True, verbose_name='Execution Reference Catalog'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_astrometry',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True, verbose_name='Execution PRAIA Astrometry'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_header',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True, verbose_name='Execution Header Extraction'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_plots',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True, verbose_name='Execution Plots'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_registry',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True, verbose_name='Execution Registry'),
        ),
        migrations.AlterField(
            model_name='astrometryasteroid',
            name='execution_targets',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True, verbose_name='Execution PRAIA Targets'),
        ),
    ]
