# Generated by Django 3.2.18 on 2024-03-01 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skybot", "0001_initial"),
        ("tno", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ccd",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Unique identifier for each CCD. desfile_id in DES database.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="CCD Id",
                    ),
                ),
                (
                    "ccdnum",
                    models.IntegerField(
                        help_text="CCD Number (1, 2, ..., 62)", verbose_name="CCD"
                    ),
                ),
                (
                    "ra_cent",
                    models.FloatField(
                        help_text="Right ascension of the CCD center", verbose_name="RA"
                    ),
                ),
                (
                    "dec_cent",
                    models.FloatField(
                        help_text="Declination of the CCD center", verbose_name="Dec"
                    ),
                ),
                (
                    "rac1",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 1 - upper left.",
                        verbose_name="rac1",
                    ),
                ),
                (
                    "rac2",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 2 - lower left.",
                        verbose_name="rac2",
                    ),
                ),
                (
                    "rac3",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 3 - lower right.",
                        verbose_name="rac3",
                    ),
                ),
                (
                    "rac4",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 4 - upper right).",
                        verbose_name="rac4",
                    ),
                ),
                (
                    "decc1",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 1 - upper left.",
                        verbose_name="decc1",
                    ),
                ),
                (
                    "decc2",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 2 - lower left.",
                        verbose_name="decc2",
                    ),
                ),
                (
                    "decc3",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 3 - lower right.",
                        verbose_name="decc3",
                    ),
                ),
                (
                    "decc4",
                    models.FloatField(
                        help_text="CCD Corner Coordinates 4 - upper right).",
                        verbose_name="decc4",
                    ),
                ),
                (
                    "crossra0",
                    models.BooleanField(default=False, verbose_name="Cross RA 0"),
                ),
                (
                    "racmin",
                    models.FloatField(
                        help_text="Minimal and maximum right ascension respectively of the CCD cover.",
                        verbose_name="racmin",
                    ),
                ),
                (
                    "racmax",
                    models.FloatField(
                        help_text="Minimal and maximum right ascension respectively of the CCD cover.",
                        verbose_name="racmax",
                    ),
                ),
                (
                    "deccmin",
                    models.FloatField(
                        help_text="Minimum and maximum declination respectively of the CCD cover.",
                        verbose_name="deccmin",
                    ),
                ),
                (
                    "deccmax",
                    models.FloatField(
                        help_text="Minimum and maximum declination respectively of the CCD cover.",
                        verbose_name="deccmax",
                    ),
                ),
                (
                    "ra_size",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="CCD dimensions in degrees (width × height).",
                        max_digits=10,
                        verbose_name="ra_size",
                    ),
                ),
                (
                    "dec_size",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="CCD dimensions in degrees (width × height).",
                        max_digits=10,
                        verbose_name="dec_size",
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        help_text="Path in the DES database where the image is stored.",
                        verbose_name="Path",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Name of FITS file with a CCD image.",
                        max_length=256,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "compression",
                    models.CharField(
                        help_text="Compression format (.fz) used in FITS files",
                        max_length=5,
                        verbose_name="Compression",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exposure",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Unique identifier for each image. expnum in DES database.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Expnum",
                    ),
                ),
                (
                    "nite",
                    models.DateField(
                        help_text="Night at which the observation was made.",
                        verbose_name="Night",
                    ),
                ),
                (
                    "date_obs",
                    models.DateTimeField(
                        help_text="Date and time of observation",
                        verbose_name="Observation Date",
                    ),
                ),
                (
                    "pfw_attempt_id",
                    models.BigIntegerField(default=0, verbose_name="Pfw Attempt Id"),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("u", "u"),
                            ("g", "g"),
                            ("r", "r"),
                            ("i", "i"),
                            ("z", "z"),
                            ("Y", "Y"),
                        ],
                        help_text="Filter used to do the observation (u, g, r, i, z, Y).",
                        max_length=1,
                        verbose_name="Filter",
                    ),
                ),
                ("radeg", models.FloatField(verbose_name="RA (deg)")),
                ("decdeg", models.FloatField(verbose_name="Dec (deg)")),
                (
                    "exptime",
                    models.FloatField(
                        help_text="Exposure time of observation.",
                        verbose_name="Exposure time",
                    ),
                ),
                (
                    "cloud_apass",
                    models.FloatField(
                        help_text="Atmospheric extinction in magnitudes",
                        verbose_name="Cloud apass",
                    ),
                ),
                (
                    "cloud_nomad",
                    models.FloatField(
                        help_text="Atmospheric extinction in magnitudes",
                        verbose_name="Cloud nomad",
                    ),
                ),
                (
                    "t_eff",
                    models.FloatField(
                        help_text="Parameter related to image quality",
                        verbose_name="t_eff",
                    ),
                ),
                (
                    "release",
                    models.CharField(
                        help_text="Release has been retrieve from the ccd filename field. using this rule trim(split_part(path , /, 3))",
                        max_length=10,
                        verbose_name="Release",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccd_id",
                    models.IntegerField(
                        default=0,
                        help_text="Field that identifies an CCD in the DES CCD table. represents desfile_id",
                        verbose_name="CCD",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="(ucd=“meta.id;meta.main”) Object name (official or provisional designation).",
                        max_length=32,
                        verbose_name="Name",
                    ),
                ),
                (
                    "date_obs",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date and time of observation already applied the DES correction.",
                        verbose_name="Observation Date",
                    ),
                ),
                (
                    "date_jd",
                    models.CharField(
                        help_text="Date and time of observation in Julian date already applied the DES correction.",
                        max_length=50,
                        verbose_name="Observation Date (JD)",
                    ),
                ),
                ("ra", models.FloatField(verbose_name="RA (deg)")),
                ("dec", models.FloatField(verbose_name="Dec (deg)")),
                ("offset_ra", models.FloatField(verbose_name="Offset RA (deg)")),
                ("offset_dec", models.FloatField(verbose_name="Offset Dec (deg)")),
                (
                    "mag_psf",
                    models.FloatField(blank=True, null=True, verbose_name="Mag PSF"),
                ),
                (
                    "mag_psf_err",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Mag PSF Error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrbitTraceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Idle"),
                            (2, "Running"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Aborted"),
                            (6, "Warning"),
                            (7, "Aborting"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submit Time"),
                ),
                (
                    "start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Start"),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finish"),
                ),
                (
                    "exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "estimated_execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Estimated Execution Time"
                    ),
                ),
                (
                    "match_radius",
                    models.FloatField(
                        default=2,
                        help_text="Exposure time of observation.",
                        verbose_name="Match Radius",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("name", "Object name"),
                            ("dynclass", "Dynamic class (with subclasses)"),
                            ("base_dynclass", "Dynamic class"),
                        ],
                        max_length=15,
                        verbose_name="Filter Type",
                    ),
                ),
                ("filter_value", models.TextField(verbose_name="Filter Value")),
                (
                    "count_asteroids",
                    models.IntegerField(
                        default=0,
                        help_text="Total asteroids selected to run this job",
                        verbose_name="Asteroids",
                    ),
                ),
                (
                    "count_ccds",
                    models.IntegerField(
                        default=0,
                        help_text="Total ccds processed in this job.",
                        verbose_name="CCDs",
                    ),
                ),
                (
                    "count_observations",
                    models.IntegerField(
                        default=0,
                        help_text="Total observations identified by the orbit trace.",
                        verbose_name="Observations Count",
                    ),
                ),
                (
                    "count_success",
                    models.IntegerField(
                        default=0,
                        help_text="Total asteroids successfully executed in all steps.",
                        verbose_name="Success",
                    ),
                ),
                (
                    "count_failures",
                    models.IntegerField(
                        default=0,
                        help_text="Total asteroids that failed at least one of the steps.",
                        verbose_name="Failures Count",
                    ),
                ),
                (
                    "h_exec_time",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Execution Time formated with humanize.",
                        max_length=100,
                        null=True,
                        verbose_name="Human Exec Time",
                    ),
                ),
                (
                    "debug",
                    models.BooleanField(
                        default=False,
                        help_text="Debug False all log files and intermediate results will be deleted at the end of the job.",
                        verbose_name="Debug",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the directory where the job data is located.",
                        max_length=2048,
                        null=True,
                        verbose_name="Path",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "traceback",
                    models.TextField(blank=True, null=True, verbose_name="Traceback"),
                ),
                (
                    "avg_exec_time_asteroid",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="average execution time per asteroid. (seconds)",
                        null=True,
                        verbose_name="Average Execution Time Asteroid",
                    ),
                ),
                (
                    "avg_exec_time_ccd",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="average execution time per ccd. (seconds)",
                        null=True,
                        verbose_name="Average Execution Time CCD",
                    ),
                ),
                (
                    "bsp_planetary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.bspplanetary",
                        verbose_name="Planetary Ephemeris",
                    ),
                ),
                (
                    "leap_seconds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.leapsecond",
                        verbose_name="Leap Second",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="des_orbitTrace_run",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkybotByDynclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dynclass",
                    models.CharField(
                        choices=[
                            ("Centaur", "Centaur"),
                            ("Comet", "Comet"),
                            ("Hungaria", "Hungaria"),
                            ("KBO", "KBO"),
                            ("MB", "MB"),
                            ("Mars-Crosser", "Mars-Crosser"),
                            ("NEA", "NEA"),
                            ("Planet", "Planet"),
                            ("Trojan", "Trojan"),
                        ],
                        max_length=12,
                        unique=True,
                        verbose_name="Dynamic Class",
                    ),
                ),
                ("nights", models.IntegerField(default=0, verbose_name="Nights")),
                ("ccds", models.IntegerField(default=0, verbose_name="CCDs")),
                ("asteroids", models.IntegerField(default=0, verbose_name="Asteroids")),
                ("positions", models.IntegerField(default=0, verbose_name="Positions")),
                ("u", models.IntegerField(default=0, verbose_name="Band u")),
                ("g", models.IntegerField(default=0, verbose_name="Band g")),
                ("r", models.IntegerField(default=0, verbose_name="Band r")),
                ("i", models.IntegerField(default=0, verbose_name="Band i")),
                ("z", models.IntegerField(default=0, verbose_name="Band z")),
                ("y", models.IntegerField(default=0, verbose_name="Band Y")),
            ],
        ),
        migrations.CreateModel(
            name="SkybotByYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2012", "2012"),
                            ("2013", "2013"),
                            ("2014", "2014"),
                            ("2015", "2015"),
                            ("2016", "2016"),
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                        ],
                        max_length=4,
                        unique=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "nights",
                    models.IntegerField(
                        default=0, verbose_name="Nights with exposures"
                    ),
                ),
                ("exposures", models.IntegerField(default=0, verbose_name="Exposures")),
                (
                    "ccds",
                    models.IntegerField(default=0, verbose_name="CCDs with exposures"),
                ),
                (
                    "nights_analyzed",
                    models.IntegerField(default=0, verbose_name="Nights analyzed"),
                ),
                (
                    "exposures_analyzed",
                    models.IntegerField(default=0, verbose_name="Exposures analyzed"),
                ),
                (
                    "ccds_analyzed",
                    models.IntegerField(default=0, verbose_name="CCDs analyzed"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkybotJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_initial", models.DateField(verbose_name="Date Initial")),
                ("date_final", models.DateField(verbose_name="Date Final")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Idle"),
                            (2, "Running"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Aborted"),
                            (6, "Warning"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submit Time"),
                ),
                (
                    "start",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start"),
                ),
                (
                    "finish",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finish"),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "estimated_execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Estimated Execution Time"
                    ),
                ),
                (
                    "exposures",
                    models.BigIntegerField(
                        default=0,
                        help_text="total exposures that were run in this job",
                        verbose_name="Exposures",
                    ),
                ),
                (
                    "ccds",
                    models.BigIntegerField(
                        default=0,
                        help_text="total ccds in the period of this job",
                        verbose_name="CCDs",
                    ),
                ),
                (
                    "nights",
                    models.BigIntegerField(
                        default=0,
                        help_text="total nights with exhibitions in the period of this job.",
                        verbose_name="Nights",
                    ),
                ),
                (
                    "positions",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total positions returned by skybot that are in DES ccds.",
                        verbose_name="Positions",
                    ),
                ),
                (
                    "asteroids",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total unique objects returned by skybot",
                        verbose_name="Asteroids",
                    ),
                ),
                (
                    "exposures_with_asteroid",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total Exposures that have at least one object through the skybot",
                        verbose_name="Exposures with Asteroid",
                    ),
                ),
                (
                    "ccds_with_asteroid",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total CCDs that have at least one object through the skybot",
                        verbose_name="CCDs with Asteroid",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path to the directory where the job data is located.",
                        max_length=2048,
                        verbose_name="Path",
                    ),
                ),
                (
                    "results",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Filepath to the results.csv. this file contains the results of the job.",
                        max_length=2048,
                        null=True,
                        verbose_name="Results",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "debug",
                    models.BooleanField(
                        default=False,
                        help_text="debug = False The files returned by skybot will be removed at the end of the job.",
                        verbose_name="Debug",
                    ),
                ),
                (
                    "summary",
                    models.BooleanField(
                        default=True,
                        help_text="summary = True runs the methods that populate the job statistics tables.",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="des_skybot_run",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryDynclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dynclass", models.TextField(verbose_name="Dynamic Class")),
                ("asteroids", models.IntegerField(verbose_name="Number of Asteroids")),
                ("ccds", models.IntegerField(verbose_name="Number of CCDs")),
                ("positions", models.IntegerField(verbose_name="Number of Positions")),
                ("u", models.IntegerField(verbose_name="Number of SSOs at u Band")),
                ("g", models.IntegerField(verbose_name="Number of SSOs at g Band")),
                ("r", models.IntegerField(verbose_name="Number of SSOs at r Band")),
                ("i", models.IntegerField(verbose_name="Number of SSOs at i Band")),
                ("z", models.IntegerField(verbose_name="Number of SSOs at z Band")),
                ("y", models.IntegerField(verbose_name="Number of SSOs at Y Band")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_summary_dynclass",
                        to="des.skybotjob",
                        verbose_name="Skybot Job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkybotPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.BigIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Id of the request made in the skybot. it serves to group all the positions that are of the same request.",
                        verbose_name="Skybot Ticket",
                    ),
                ),
                (
                    "ccd",
                    models.ForeignKey(
                        help_text="Field that identifies an CCD in the DES CCD table. represents desfile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="des.ccd",
                        verbose_name="CCD",
                    ),
                ),
                (
                    "exposure",
                    models.ForeignKey(
                        help_text="Field that identifies an exposure in the Pointings table. represents pfw_attempt_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="des.exposure",
                        verbose_name="Exposure",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Represents a specific position in the Skybot result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skybot.position",
                        verbose_name="Position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkybotJobResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.BigIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Id of the request made in the skybot. it serves to group all the positions that are of the same request.",
                        verbose_name="Skybot Ticket",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="true if the exposure was successfully executed.",
                        verbose_name="Success",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "ccds_with_asteroids",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of CCDs with Asteroids for this exposure",
                        verbose_name="CCDs With Asteroids",
                    ),
                ),
                (
                    "positions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions returned by skybot for this exposure",
                        verbose_name="Positions",
                    ),
                ),
                (
                    "inside_ccd",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions that are within any ccd of this exposure.",
                        verbose_name="Inside CCD",
                    ),
                ),
                (
                    "outside_ccd",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions are not in any ccd of this exposure.",
                        verbose_name="Outside CCD",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="name of the file with the results returned by skybot.",
                        max_length=100,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "exposure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="des.exposure",
                        verbose_name="Exposure",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_results",
                        to="des.skybotjob",
                        verbose_name="Skybot Job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrbitTraceJobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        help_text="Identification of the step in the pipeline.",
                        verbose_name="Step",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        default="",
                        help_text="Name of the task being executed.",
                        max_length=100,
                        verbose_name="Task",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Idle"),
                            (2, "Running"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Aborted"),
                            (6, "Warning"),
                            (7, "Aborting"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Total items to be processed in the step.",
                        verbose_name="Total Count",
                    ),
                ),
                (
                    "current",
                    models.IntegerField(
                        default=0,
                        help_text="Current position in execution.",
                        verbose_name="Current",
                    ),
                ),
                (
                    "average_time",
                    models.FloatField(
                        default=0,
                        help_text="Average time per item in seconds.",
                        verbose_name="Average Time",
                    ),
                ),
                (
                    "time_estimate",
                    models.FloatField(
                        default=0,
                        help_text="Estimated time to complete the step in seconds.",
                        verbose_name="Estimated Time",
                    ),
                ),
                (
                    "success",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items successfully executed.",
                        verbose_name="Success",
                    ),
                ),
                (
                    "failures",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items that failed.",
                        verbose_name="Failures",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_status",
                        to="des.orbittracejob",
                        verbose_name="Orbit Trace Job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrbitTraceJobResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Asteroid Name"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Asteroid Number",
                    ),
                ),
                (
                    "base_dynclass",
                    models.CharField(
                        max_length=100, verbose_name="Asteroid Base DynClass"
                    ),
                ),
                (
                    "dynclass",
                    models.CharField(max_length=100, verbose_name="Asteroid DynClass"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Success"), (2, "Failed")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "spk_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Spk Id"
                    ),
                ),
                (
                    "observations",
                    models.IntegerField(
                        default=0,
                        help_text="Observations Count",
                        verbose_name="Observations Count",
                    ),
                ),
                (
                    "ccds",
                    models.IntegerField(
                        default=0, help_text="CCDS Count", verbose_name="CCDS Count"
                    ),
                ),
                (
                    "exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "asteroid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tno.asteroid",
                        verbose_name="Asteroid",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="des.orbittracejob",
                        verbose_name="Orbit Trace Job",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["name"], name="des_observa_name_13e3e4_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["date_obs"], name="des_observa_date_ob_284449_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="observation",
            unique_together={("name", "ccd_id")},
        ),
        migrations.AddIndex(
            model_name="exposure",
            index=models.Index(fields=["nite"], name="des_exposur_nite_bbf059_idx"),
        ),
        migrations.AddIndex(
            model_name="exposure",
            index=models.Index(
                fields=["date_obs"], name="des_exposur_date_ob_f351f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exposure",
            index=models.Index(
                fields=["release"], name="des_exposur_release_c66eaf_idx"
            ),
        ),
        migrations.AddField(
            model_name="ccd",
            name="exposure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="des.exposure",
                verbose_name="Exposure",
            ),
        ),
        migrations.AddIndex(
            model_name="summarydynclass",
            index=models.Index(
                fields=["dynclass"], name="des_summary_dynclas_b5a895_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skybotposition",
            unique_together={("position", "exposure", "ccd")},
        ),
        migrations.AddIndex(
            model_name="ccd",
            index=models.Index(fields=["filename"], name="des_ccd_filenam_acd904_idx"),
        ),
    ]
