# Generated by Django 2.0.12 on 2020-07-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0010_auto_20200702_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadccdjobresult",
            name="ccd",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="des.Ccd",
                verbose_name="CCD",
            ),
        ),
    ]
