# Generated by Django 2.0.12 on 2020-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0019_auto_20200828_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="skybotjob",
            name="exposures_analyzed",
            field=models.BigIntegerField(
                default=0,
                help_text="Total Exposures that have at least one object through the skybot",
                verbose_name="Exposures analyzed",
            ),
        ),
    ]
