# Generated by Django 2.0.12 on 2020-09-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0020_skybotjob_exposures_analyzed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skybotjob",
            name="exposures_analyzed",
        ),
    ]
