# Generated by Django 2.0.12 on 2020-10-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0024_merge_20201014_1701"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDynclass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dynclass", models.TextField(verbose_name="Dynamic Class")),
                ("asteroids", models.IntegerField(verbose_name="Number of Asteroids")),
                ("ccds", models.IntegerField(verbose_name="Number of CCDs")),
                ("positions", models.IntegerField(verbose_name="Number of Positions")),
                ("u", models.IntegerField(verbose_name="Number of SSOs at u Band")),
                ("g", models.IntegerField(verbose_name="Number of SSOs at g Band")),
                ("r", models.IntegerField(verbose_name="Number of SSOs at r Band")),
                ("i", models.IntegerField(verbose_name="Number of SSOs at i Band")),
                ("z", models.IntegerField(verbose_name="Number of SSOs at z Band")),
                ("y", models.IntegerField(verbose_name="Number of SSOs at Y Band")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_summary_dynclass",
                        to="des.SkybotJob",
                        verbose_name="Skybot Job",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="summarydynclass",
            index=models.Index(
                fields=["dynclass"], name="des_summary_dynclas_b5a895_idx"
            ),
        ),
    ]
