# Generated by Django 2.0.12 on 2020-11-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0026_dashboardskybotdynclassresult_dashboardskybotyearresult"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DashboardSkybotDynclassResult",
            new_name="SkybotByDynclass",
        ),
        migrations.RenameModel(
            old_name="DashboardSkybotYearResult",
            new_name="SkybotByYear",
        ),
    ]
