# Generated by Django 2.2.13 on 2022-11-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0035_auto_20210810_2053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadccdjobresult",
            name="ccd",
        ),
        migrations.RemoveField(
            model_name="downloadccdjobresult",
            name="job",
        ),
        migrations.DeleteModel(
            name="DownloadCcdJob",
        ),
        migrations.DeleteModel(
            name="DownloadCcdJobResult",
        ),
    ]
