# Generated by Django 3.2 on 2023-01-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0037_auto_20221118_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AstrometryJob',
        ),
    ]
