# Generated by Django 3.2 on 2023-02-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0039_auto_20230131_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="skybotjob",
            name="debug",
            field=models.BooleanField(default=False, verbose_name="Debug"),
        ),
    ]
