# Generated by Django 3.2 on 2023-02-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("des", "0039_auto_20230131_1617"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrbitTraceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_initial", models.DateField(verbose_name="Date Initial")),
                ("date_final", models.DateField(verbose_name="Date Final")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Idle"),
                            (2, "Running"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Aborted"),
                            (6, "Warning"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start"),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finish"),
                ),
                (
                    "exec_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "estimated_execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Estimated Execution Time"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path to the directory where the job data is located.",
                        max_length=2048,
                        verbose_name="Path",
                    ),
                ),
                (
                    "results",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Filepath to the results.csv. this file contains the results of the job.",
                        max_length=2048,
                        null=True,
                        verbose_name="Results",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="des_orbitTrace_run",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
    ]
