# Generated by Django 3.2.18 on 2023-02-23 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0041_auto_20230215_2328"),
    ]

    operations = [
        migrations.AddField(
            model_name="skybotjob",
            name="submit_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Submit Time",
            ),
            preserve_default=False,
        ),
    ]
