# Generated by Django 3.2 on 2023-02-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0042_auto_20230216_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="orbittracejob",
            name="filter_type",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Filter Type"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="filter_value",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Filter Type"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="processed_asteroids",
            field=models.IntegerField(
                default=0,
                help_text="Processed Asteroids",
                verbose_name="Processed Asteroids",
            ),
        ),
    ]
