# Generated by Django 3.2 on 2023-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0046_orbittracejob_observatory_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="orbittracejob",
            name="time_profile",
            field=models.JSONField(default="[]"),
            preserve_default=False,
        ),
    ]
