# Generated by Django 3.2.18 on 2023-02-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0041_auto_20230215_2328'),
        ('des', '0048_auto_20230216_2057'),
    ]

    operations = [
    ]
