# Generated by Django 3.2.18 on 2023-02-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0042_skybotjob_submit_time'),
        ('des', '0049_merge_0041_auto_20230215_2328_0048_auto_20230216_2057'),
    ]

    operations = [
    ]
