# Generated by Django 3.2.18 on 2023-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0050_merge_20230228_2107"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orbittracejob",
            name="date_final",
        ),
        migrations.RemoveField(
            model_name="orbittracejob",
            name="date_initial",
        ),
        migrations.RemoveField(
            model_name="orbittracejob",
            name="expected_asteroids",
        ),
        migrations.RemoveField(
            model_name="orbittracejob",
            name="observatory_location",
        ),
        migrations.RemoveField(
            model_name="orbittracejob",
            name="processed_asteroids",
        ),
        migrations.RemoveField(
            model_name="orbittracejob",
            name="results",
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="bps_days_to_expire",
            field=models.IntegerField(
                default=0,
                help_text="bps_days_to_expire",
                verbose_name="bps_days_to_expire",
            ),
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="debug",
            field=models.BooleanField(
                default=False, help_text="Debug", verbose_name="Debug"
            ),
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="path",
            field=models.CharField(
                default=1,
                help_text="Path to the directory where the job data is located.",
                max_length=2048,
                verbose_name="Path",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orbittracejob",
            name="filter_value",
            field=models.CharField(max_length=100, verbose_name="Filter Value"),
        ),
    ]
