# Generated by Django 3.2.18 on 2023-03-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0052_orbittracejobresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orbittracejobresult",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="des.orbittracejob",
                verbose_name="Orbit Trace Job",
            ),
        ),
    ]
