# Generated by Django 3.2.18 on 2023-03-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0054_alter_orbittracejob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orbittracejob",
            name="h_exec_time",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="h_exec_time",
                null=True,
                verbose_name="h_exec_time",
            ),
        ),
        migrations.AlterField(
            model_name="orbittracejob",
            name="parsl_init_blocks",
            field=models.IntegerField(
                default=400,
                help_text="parsl_init_blocks",
                verbose_name="parsl_init_blocks",
            ),
        ),
        migrations.AlterField(
            model_name="orbittracejob",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Path to the directory where the job data is located.",
                max_length=2048,
                null=True,
                verbose_name="Path",
            ),
        ),
    ]
