# Generated by Django 3.2.18 on 2023-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0058_auto_20230331_1942"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orbittracejob",
            name="time_profile",
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="condor_job_completed",
            field=models.IntegerField(
                default=0,
                help_text="HTCondor Jobs Completed.",
                verbose_name="HTCondor Completed",
            ),
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="condor_job_removed",
            field=models.IntegerField(
                default=0,
                help_text="Condor Jobs Removed",
                verbose_name="HTCondor Removed",
            ),
        ),
        migrations.AddField(
            model_name="orbittracejob",
            name="condor_job_submited",
            field=models.IntegerField(
                default=0,
                help_text="HTCondor Job Submited",
                verbose_name="HTCondor Jobs",
            ),
        ),
        migrations.AlterField(
            model_name="orbittracejob",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("name", "Name"),
                    ("dynclass", "DynClass"),
                    ("base_dynclass", "Base DynClass"),
                ],
                max_length=15,
                verbose_name="Filter Type",
            ),
        ),
        migrations.AlterField(
            model_name="orbittracejob",
            name="filter_value",
            field=models.TextField(verbose_name="Filter Value"),
        ),
    ]
