# Generated by Django 3.2.18 on 2023-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0062_alter_observation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created at"),
        ),
    ]
