# Generated by Django 3.2.18 on 2023-05-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0063_observation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orbittracejob',
            name='condor_job_completed',
        ),
        migrations.RemoveField(
            model_name='orbittracejob',
            name='condor_job_removed',
        ),
        migrations.RemoveField(
            model_name='orbittracejob',
            name='condor_job_submited',
        ),
        migrations.AddField(
            model_name='orbittracejob',
            name='avg_exec_time_asteroid',
            field=models.FloatField(blank=True, default=0, help_text='average execution time per asteroid. (seconds)', null=True, verbose_name='Average Execution Time Asteroid'),
        ),
        migrations.AddField(
            model_name='orbittracejob',
            name='avg_exec_time_ccd',
            field=models.FloatField(blank=True, default=0, help_text='average execution time per ccd. (seconds)', null=True, verbose_name='Average Execution Time CCD'),
        ),
    ]
