# Generated by Django 3.2.18 on 2023-05-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0064_auto_20230531_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orbittracejob',
            name='bps_days_to_expire',
        ),
        migrations.RemoveField(
            model_name='orbittracejob',
            name='parsl_init_blocks',
        ),
        migrations.AlterField(
            model_name='orbittracejob',
            name='filter_type',
            field=models.CharField(choices=[('name', 'Object name'), ('dynclass', 'Dynamic class (with subclasses)'), ('base_dynclass', 'Dynamic class')], max_length=15, verbose_name='Filter Type'),
        ),
    ]
