# Generated by Django 3.2.18 on 2023-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0065_auto_20230531_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbittracejobresult',
            name='exec_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
    ]
