# Generated by Django 3.2.18 on 2023-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0068_auto_20230605_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orbittracejobstatus",
            name="task",
            field=models.CharField(
                default="",
                help_text="Name of the task being executed.",
                max_length=100,
                verbose_name="Task",
            ),
        ),
    ]
