SELECT
t3.FILENAME,
t3.COMPRESSION,
t3.PATH,
t3.DESFILE_ID,
t2.PFW_ATTEMPT_ID,
t2.BAND,
t2.CCDNUM,
t4.DATE_OBS, t4.EXPTIME,
t4.RADEG,
t4.DECDEG,
t5.CLOUD_APASS,
t5.CLOUD_NOMAD,
t5.T_EFF,
t2.NITE,
t2.EXPNUM,
t2.CROSSRA0,
t2.RACMIN, t2.RACMAX,
t2.DECCMIN, t2.DECCMAX,
t2.RA_CENT, t2.DEC_CENT,
t2.RAC1, t2.RAC2, t2.RAC3, t2.RAC4,
t2.DECC1, t2.DECC2, t2.DECC3, t2.DECC4,
(case when t2.CROSSRA0='Y' THEN abs(t2.RACMAX - (t2.RACMIN-360))
ELSE abs(t2.RACMAX - t2.RACMIN) END) as RA_SIZE, abs(t2.DECCMAX - t2.DECCMIN) as DEC_SIZE
FROM
Y6A1_PROCTAG t1, Y6A1_IMAGE t2, Y6A1_FILE_ARCHIVE_INFO t3, Y6A1_EXPOSURE t4, Y6A1_QA_SUMMARY t5
WHERE
t2.EXPNUM = t4.EXPNUM AND
t2.PFW_ATTEMPT_ID = t5.PFW_ATTEMPT_ID AND
t3.FILENAME = t2.FILENAME AND
t2.PFW_ATTEMPT_ID = t1.PFW_ATTEMPT_ID AND
t2.FILETYPE = 'red_immask' AND
t1.TAG = 'Y6A1_FINALCUT'
order by t4.DATE_OBS; > Y6A1_CCDsMetadata.csv
