# Generated by Django 2.0.12 on 2020-05-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tno', '0017_auto_20200504_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkybotPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure', models.BigIntegerField(help_text='Field that identifies an exposure in the Pointings table. refers to pfw_attempt_id.', verbose_name='Exposure')),
                ('ccd', models.ForeignKey(help_text='Field that identifies an CCD in the Pointings table. refers to desfile_id.', on_delete=django.db.models.deletion.CASCADE, related_name='skybot_position_ccd', to='tno.Pointing', to_field='desfile_id', verbose_name='CCD')),
                ('position', models.ForeignKey(help_text='Represents a specific position in the Skybot result.', on_delete=django.db.models.deletion.CASCADE, to='tno.SkybotOutput', verbose_name='Position')),
            ],
        ),
    ]
