# Generated by Django 2.0.12 on 2020-06-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkybotJobResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.BigIntegerField(
                        default=0,
                        help_text="Id of the request made in the skybot. it serves to group all the positions that are of the same request.",
                        verbose_name="Skybot Ticket",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="true if the exposure was successfully executed.",
                        verbose_name="Success",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Execution Time"
                    ),
                ),
                (
                    "positions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions returned by skybot for this exhibition",
                        verbose_name="Positions",
                    ),
                ),
                (
                    "inside_ccd",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions that are within any ccd of this exposure.",
                        verbose_name="Inside CCD",
                    ),
                ),
                (
                    "outside_ccd",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="number of positions are not in any ccd of this exposure.",
                        verbose_name="Outside CCD",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="name of the file with the results returned by skybot.",
                        max_length=100,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "exposure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="des.Exposure",
                        verbose_name="Exposure",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_results",
                        to="des.SkybotJob",
                        verbose_name="Skybot Job",
                    ),
                ),
            ],
        ),
    ]
