# Generated by Django 2.0.12 on 2020-05-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigIntegerField(help_text='Unique identifier for each image. pfw_attempt_id in DES database.', primary_key=True, serialize=False, verbose_name='Exposure Id')),
                ('nite', models.DateField(help_text='Night at which the observation was made.', verbose_name='Night')),
                ('date_obs', models.DateTimeField(help_text='Date and time of observation', verbose_name='Observation Date')),
                ('expnum', models.BigIntegerField(help_text='identifier for each image. (it also recorded in the file name)', verbose_name='Expnum')),
                ('radeg', models.FloatField(verbose_name='RA (deg)')),
                ('decdeg', models.FloatField(verbose_name='Dec (deg)')),
                ('exptime', models.FloatField(help_text='Exposure time of observation.', verbose_name='Exposure time')),
                ('cloud_apass', models.FloatField(help_text='Atmospheric extinction in magnitudes', verbose_name='Cloud apass')),
                ('cloud_nomad', models.FloatField(help_text='Atmospheric extinction in magnitudes', verbose_name='Cloud nomad')),
                ('t_eff', models.FloatField(help_text='Parameter related to image quality', verbose_name='t_eff')),
                ('release', models.CharField(help_text='Release has been removed from the ccd filename field. using this rule trim(split_part(path , /, 3))', max_length=10, verbose_name='Release')),
            ],
        ),
    ]
