# Generated by Django 2.0.12 on 2020-05-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0002_exposure'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['nite'], name='des_exposur_nite_bbf059_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['date_obs'], name='des_exposur_date_ob_f351f0_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['release'], name='des_exposur_release_c66eaf_idx'),
        ),
    ]
