# Generated by Django 2.0.12 on 2020-05-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0003_auto_20200504_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='band',
            field=models.CharField(choices=[('u', 'u'), ('g', 'g'), ('r', 'r'), ('i', 'i'), ('z', 'z'), ('Y', 'Y')], default=None, help_text='Filter used to do the observation (u, g, r, i, z, Y).', max_length=1, verbose_name='Filter'),
            preserve_default=False,
        ),
    ]
