# Generated by Django 2.0.12 on 2020-06-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0004_auto_20200611_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skybotjob',
            unique_together=set(),
        ),
    ]
