# Generated by Django 2.0.12 on 2020-05-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0004_exposure_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccd',
            fields=[
                ('id', models.BigIntegerField(help_text='Unique identifier for each CCD. desfile_id in DES database.', primary_key=True, serialize=False, verbose_name='CCD Id')),
                ('ccdnum', models.IntegerField(help_text='CCD Number (1, 2, ..., 62)', verbose_name='CCD')),
                ('ra_cent', models.FloatField(help_text='Right ascension of the CCD center', verbose_name='RA')),
                ('dec_cent', models.FloatField(help_text='Declination of the CCD center', verbose_name='Dec')),
                ('rac1', models.FloatField(help_text='CCD Corner Coordinates 1 - upper left.', verbose_name='rac1')),
                ('rac2', models.FloatField(help_text='CCD Corner Coordinates 2 - lower left.', verbose_name='rac2')),
                ('rac3', models.FloatField(help_text='CCD Corner Coordinates 3 - lower right.', verbose_name='rac3')),
                ('rac4', models.FloatField(help_text='CCD Corner Coordinates 4 - upper right).', verbose_name='rac4')),
                ('decc1', models.FloatField(help_text='CCD Corner Coordinates 1 - upper left.', verbose_name='decc1')),
                ('decc2', models.FloatField(help_text='CCD Corner Coordinates 2 - lower left.', verbose_name='decc2')),
                ('decc3', models.FloatField(help_text='CCD Corner Coordinates 3 - lower right.', verbose_name='decc3')),
                ('decc4', models.FloatField(help_text='CCD Corner Coordinates 4 - upper right).', verbose_name='decc4')),
                ('crossra0', models.BooleanField(default=False, verbose_name='Cross RA 0')),
                ('racmin', models.FloatField(help_text='Minimal and maximum right ascension respectively of the CCD cover.', verbose_name='racmin')),
                ('racmax', models.FloatField(help_text='Minimal and maximum right ascension respectively of the CCD cover.', verbose_name='racmax')),
                ('deccmin', models.FloatField(help_text='Minimum and maximum declination respectively of the CCD cover.', verbose_name='deccmin')),
                ('deccmax', models.FloatField(help_text='Minimum and maximum declination respectively of the CCD cover.', verbose_name='deccmax')),
                ('ra_size', models.DecimalField(decimal_places=7, help_text='CCD dimensions in degrees (width × height).', max_digits=10, verbose_name='ra_size')),
                ('dec_size', models.DecimalField(decimal_places=7, help_text='CCD dimensions in degrees (width × height).', max_digits=10, verbose_name='dec_size')),
                ('path', models.TextField(help_text='Path in the DES database where the image is stored.', verbose_name='Path')),
                ('filename', models.CharField(help_text='Name of FITS file with a CCD image.', max_length=256, verbose_name='Filename')),
                ('compression', models.CharField(help_text='Compression format (.fz) used in FITS files', max_length=5, verbose_name='Compression')),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='des.Exposure', verbose_name='Exposure')),
            ],
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['filename'], name='des_ccd_filenam_acd904_idx'),
        ),
    ]
