# Generated by Django 2.0.12 on 2020-05-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0005_auto_20200505_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skybotposition',
            name='ccd',
        ),
        migrations.RemoveField(
            model_name='skybotposition',
            name='position',
        ),
        migrations.DeleteModel(
            name='SkybotPosition',
        ),
    ]
