# Generated by Django 2.0.12 on 2020-05-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0017_auto_20200504_2225'),
        ('des', '0006_auto_20200505_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkybotPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccd', models.ForeignKey(help_text='Field that identifies an CCD in the DES CCD table. represents desfile_id', on_delete=django.db.models.deletion.CASCADE, to='des.Ccd', verbose_name='CCD')),
                ('exposure', models.ForeignKey(help_text='Field that identifies an exposure in the Pointings table. represents pfw_attempt_id.', on_delete=django.db.models.deletion.CASCADE, to='des.Exposure', verbose_name='Exposure')),
                ('position', models.ForeignKey(help_text='Represents a specific position in the Skybot result.', on_delete=django.db.models.deletion.CASCADE, to='tno.SkybotOutput', verbose_name='Position')),
            ],
        ),
    ]
