# Generated by Django 2.0.12 on 2020-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0007_downloadccdjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadccdjob',
            name='t_size_downloaded',
            field=models.BigIntegerField(blank=True, default=0, help_text='Total size downloaded in this job.', null=True, verbose_name='Size Downloaded'),
        ),
    ]
