# Generated by Django 2.0.12 on 2020-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0017_auto_20200504_2225'),
        ('des', '0007_skybotposition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skybotposition',
            unique_together={('position', 'exposure', 'ccd')},
        ),
    ]
