# Generated by Django 2.0.12 on 2020-07-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0008_auto_20200626_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCcdJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finish')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
                ('file_size', models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size')),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='des.Ccd', verbose_name='CCD')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='des.DownloadCcdJob', verbose_name='Download CCD Job')),
            ],
        ),
    ]
