# Generated by Django 2.0.12 on 2020-05-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('des', '0008_auto_20200505_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkybotJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initial', models.DateField(verbose_name='Date Initial')),
                ('date_final', models.DateField(verbose_name='Date Final')),
                ('status', models.IntegerField(choices=[(1, 'Idle'), (2, 'Running'), (3, 'Completed'), (4, 'Failed'), (5, 'Aborted'), (6, 'Stoped')], default=1, verbose_name='Status')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finish')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
                ('exposures', models.BigIntegerField(default=0, verbose_name='Exposures')),
                ('path', models.TextField(help_text='Path to the directory where the job data is located.', verbose_name='Path')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des_skybot_run', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skybotjobs',
            unique_together={('date_initial', 'date_final')},
        ),
    ]
