# Generated by Django 2.0.12 on 2020-07-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0009_downloadccdjobresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadccdjobresult",
            old_name="exposure",
            new_name="ccd",
        ),
    ]
