# Generated by Django 2.0.12 on 2020-05-06 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('des', '0009_auto_20200506_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkybotJobs',
            new_name='SkybotJob',
        ),
    ]
