# Generated by Django 2.0.12 on 2020-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0010_auto_20200506_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotjob',
            name='results',
            field=models.CharField(blank=True, default=None, help_text='Filepath to the results.csv. this file contains the results of the job.', max_length=2048, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='skybotjob',
            name='path',
            field=models.CharField(help_text='Path to the directory where the job data is located.', max_length=2048, verbose_name='Path'),
        ),
    ]
