# Generated by Django 2.0.12 on 2020-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0011_auto_20200521_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotjob',
            name='status',
            field=models.IntegerField(choices=[(1, 'Idle'), (2, 'Running'), (3, 'Completed'), (4, 'Failed'), (5, 'Aborted'), (6, 'Stopped')], default=1, verbose_name='Status'),
        ),
    ]
