# Generated by Django 2.0.12 on 2020-05-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0011_auto_20200521_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skybotposition',
            name='position',
            field=models.ForeignKey(help_text='Represents a specific position in the Skybot result.', on_delete=django.db.models.deletion.CASCADE, to='skybot.Position', verbose_name='Position'),
        ),
    ]
