# Generated by Django 2.0.12 on 2020-07-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0012_auto_20200706_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadccdjob',
            name='path',
            field=models.CharField(blank=True, help_text='Path to the directory where the job data is located.', max_length=2048, null=True, verbose_name='Path'),
        ),
    ]
