# Generated by Django 2.0.12 on 2020-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0017_auto_20200819_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotjob',
            name='estimated_execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Estimated Execution Time'),
        ),
    ]
