# Generated by Django 2.0.12 on 2020-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0019_auto_20200828_1716"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exposure",
            name="expnum",
        ),
        migrations.AddField(
            model_name="exposure",
            name="pfw_attempt_id",
            field=models.BigIntegerField(default=0, verbose_name="Pfw Attempt Id"),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="id",
            field=models.BigIntegerField(
                help_text="Unique identifier for each image. expnum in DES database.",
                primary_key=True,
                serialize=False,
                verbose_name="Expnum",
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="release",
            field=models.CharField(
                help_text="Release has been retrieve from the ccd filename field. using this rule trim(split_part(path , /, 3))",
                max_length=10,
                verbose_name="Release",
            ),
        ),
    ]
