# Generated by Django 2.0.12 on 2020-09-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0022_auto_20200917_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybotjobresult',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
    ]
