# Generated by Django 2.0.12 on 2020-10-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0023_skybotjobresult_error'),
        ('des', '0020_auto_20200930_1532'),
    ]

    operations = [
    ]
