# Generated by Django 2.0.12 on 2020-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("des", "0025_auto_20201022_1304"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSkybotDynclassResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dynclass",
                    models.CharField(
                        choices=[
                            ("Centaur", "Centaur"),
                            ("Comet", "Comet"),
                            ("Hungaria", "Hungaria"),
                            ("KBO", "KBO"),
                            ("MB", "MB"),
                            ("Mars-Crosser", "Mars-Crosser"),
                            ("NEA", "NEA"),
                            ("Planet", "Planet"),
                            ("Trojan", "Trojan"),
                        ],
                        max_length=12,
                        unique=True,
                        verbose_name="Dynamic Class",
                    ),
                ),
                ("nights", models.IntegerField(default=0, verbose_name="Nights")),
                ("ccds", models.IntegerField(default=0, verbose_name="CCDs")),
                ("asteroids", models.IntegerField(default=0, verbose_name="Asteroids")),
                ("positions", models.IntegerField(default=0, verbose_name="Positions")),
                ("u", models.IntegerField(default=0, verbose_name="Band u")),
                ("g", models.IntegerField(default=0, verbose_name="Band g")),
                ("r", models.IntegerField(default=0, verbose_name="Band r")),
                ("i", models.IntegerField(default=0, verbose_name="Band i")),
                ("z", models.IntegerField(default=0, verbose_name="Band z")),
                ("y", models.IntegerField(default=0, verbose_name="Band Y")),
            ],
        ),
        migrations.CreateModel(
            name="DashboardSkybotYearResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2012", "2012"),
                            ("2013", "2013"),
                            ("2014", "2014"),
                            ("2015", "2015"),
                            ("2016", "2016"),
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                        ],
                        max_length=4,
                        unique=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "nights",
                    models.IntegerField(
                        default=0, verbose_name="Nights with exposures"
                    ),
                ),
                ("exposures", models.IntegerField(default=0, verbose_name="Exposures")),
                (
                    "ccds",
                    models.IntegerField(default=0, verbose_name="CCDs with exposures"),
                ),
                (
                    "nights_analyzed",
                    models.IntegerField(default=0, verbose_name="Nights analyzed"),
                ),
                (
                    "exposures_analyzed",
                    models.IntegerField(default=0, verbose_name="Exposures analyzed"),
                ),
                (
                    "ccds_analyzed",
                    models.IntegerField(default=0, verbose_name="CCDs analyzed"),
                ),
            ],
        ),
    ]
