# Generated by Django 2.2.13 on 2021-06-25 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tno', '0003_bspplanetary_leapsecond'),
        ('des', '0027_auto_20201104_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='(ucd=“meta.id;meta.main”) Object name (official or provisional designation).', max_length=32, verbose_name='Name')),
                ('date_obs', models.DateTimeField(db_index=True, help_text='Date and time of observation already applied the DES correction.', verbose_name='Observation Date')),
                ('date_jd', models.DateTimeField(help_text='Date and time of observation in Julian date already applied the DES correction.', verbose_name='Observation Date (JD)')),
                ('ra', models.FloatField(verbose_name='RA (deg)')),
                ('dec', models.FloatField(verbose_name='Dec (deg)')),
                ('offset_ra', models.FloatField(verbose_name='Offset RA (deg)')),
                ('offset_dec', models.FloatField(verbose_name='Offset Dec (deg)')),
                ('mag_psf', models.FloatField(blank=True, null=True, verbose_name='Mag PSF')),
                ('mag_psf_err', models.FloatField(blank=True, null=True, verbose_name='Mag PSF Error')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tno.Asteroid', verbose_name='Asteroid')),
                ('ccd', models.ForeignKey(help_text='Field that identifies an CCD in the DES CCD table. represents desfile_id', on_delete=django.db.models.deletion.CASCADE, to='des.Ccd', verbose_name='CCD')),
            ],
            options={
                'unique_together': {('asteroid', 'ccd')},
            },
        ),
    ]
