# Generated by Django 2.2.13 on 2021-07-13 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('des', '0029_auto_20210625_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asteroids', models.TextField(blank=True, default=None, help_text='Asteroids that will be processed can be a single asteroid name or a list separated by ;', null=True, verbose_name='Asteroids')),
                ('dynclass', models.CharField(blank=True, default=None, help_text='(ucd=“meta.code.class;src.class”) Object class (TNO, Centaur, Trojan, etc.).', max_length=24, null=True, verbose_name='Object classification')),
                ('status', models.IntegerField(choices=[(1, 'Idle'), (2, 'Running'), (3, 'Completed'), (4, 'Failed'), (5, 'Aborted'), (6, 'Warning')], default=1, verbose_name='Status')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finish')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='Execution Time')),
                ('estimated_execution_time', models.DurationField(blank=True, null=True, verbose_name='Estimated Execution Time')),
                ('t_asteroids', models.BigIntegerField(default=0, help_text='total asteroids that were run in this job', verbose_name='Total Asteroids')),
                ('path', models.CharField(help_text='Path to the directory where the job data is located.', max_length=2048, verbose_name='Path')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrometry_job', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
