# Generated by Django 2.2.13 on 2021-07-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0030_astrometryjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometryjob',
            name='path',
            field=models.CharField(blank=True, help_text='Path to the directory where the job data is located.', max_length=2048, null=True, verbose_name='Path'),
        ),
    ]
