# Generated by Django 2.2.13 on 2021-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0034_auto_20210728_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryjob',
            name='t_ccds',
            field=models.BigIntegerField(default=0, help_text='total ccds that were run in this job', verbose_name='Total CCDs'),
        ),
        migrations.AddField(
            model_name='astrometryjob',
            name='t_observations',
            field=models.BigIntegerField(default=0, help_text='Total observations processed in this job', verbose_name='Total Observations'),
        ),
    ]
